### ISSUE TITLE
how to support the Chinese character? Any suggestions?

### ISSUE THREAD

**Issue by zxforben** [yWorks/svg2pdf.js#106]
**Is your feature request related to a problem? Please describe.**
I would like to see support for this feature of SVG (pointer to SVG spec)

**Describe the solution you'd like**
How should that be implemented in PDF?

**Describe alternatives you've considered**

**Additional context**

**Comment by HackbrettXXX** [comment]
See the "Custom Fonts" section in [jsPDF's readme](https://github.com/yWorks/jsPDF).
