### ISSUE TITLE
Markers ignore a stroke-width attribute of a path

### ISSUE THREAD

**Issue by mwasiluk** [yWorks/svg2pdf.js#12]
Hi, there is a problem with rendering markers on paths with a stroke-width attribute.
An example from the slightly changed tests/test12.html:

Svg : 
![svg](https://cloud.githubusercontent.com/assets/1236142/21388937/2d8df98a-c77f-11e6-878f-36493305bfa9.PNG)

Rendered pdf : 
![pdf](https://cloud.githubusercontent.com/assets/1236142/21388941/3405eba6-c77f-11e6-91c7-e7b4dfabb1c2.PNG)

**Comment by yGuy** [comment]
OK - thanks for reporting - any idea in what way it is broken?

**Comment by yGuy** [comment]
From the spec: 

> ‘markerWidth’, ‘markerHeight’ and the contents of the ‘marker’ represent values in a coordinate system which has a single unit equal the size in user units of the current stroke width (see the ‘stroke-width’ property) in place for the graphic object referencing the marker

Basically this means: scale the markers by the stroke-width
