### ISSUE TITLE
Limit the PDF to actually used fonts

### ISSUE THREAD

**Issue by ThomasJunk** [yWorks/svg2pdf.js#122]
Hey guys,

MrRio JSDPF has an option `putOnlyUsedFonts` which limits the embedding of fonts to the actually used ones, which results in smaller PDFs - a goodie on Mobile with bad connection.

See: https://github.com/MrRio/jsPDF/blob/6c6ca0c4554eb5b6446dab9337befd6625119bee/src/jspdf.js#L86

Are there any current plans retrofitting this functionality into this fork?

I am asking only for planning purposes. If there is a foreseeable timeframe I would wait for it.

OTOH I could live without - so no actual pressure.

**Comment by ThomasJunk** [comment]
Wrong project, sorry XD

**Comment by HackbrettXXX** [comment]
We already merged this feature some time ago into this fork.
