### ISSUE TITLE
Nested <tspan /> elements

### ISSUE THREAD

**Issue by giacomarco** [yWorks/svg2pdf.js#123]
With this svg code
`<text id="text-1">
<tspan x="20" y="32">
​<tspan>lorem i</tspan>
<tspan style="font-weight: bold;">p
<tspan font-style="italic">su
<tspan text-decoration="underline">m
</tspan>
</tspan>
</tspan>
</tspan>
</text>`
i had not text
if i remove all nested tspan i had the correct pdf.

Thanks for any help.

**Comment by yGuy** [comment]
I believe nested tspan's simply aren't considered at all, at the moment. Thanks for reporting. This should not be too difficult to fix, but needs some additional state-keeping.

**Comment by giacomarco** [comment]
if I comment line **3813** 
` if (tSpan.childElementCount > 0) {
// filter <title> elements...
            // textContent = "";  <---- this line
            for (var j = 0; j < tSpan.childNodes.length; j++) {
              if (tSpan.childNodes[j].nodeName === "#text") {
                textContent += tSpan.childNodes[j].textContent;
              }
            }
          }`
i have back the text in svg but without any style, no bold no italic etc.. 
if i found other informations i'm happy to help.

**Comment by giacomarco** [comment]
@yGuy Do you have some news about this fix? I can do something for help you ?

**Comment by yGuy** [comment]
If I had news, I would post them, here. This is an open-source project and everybody is free to collaborate. Of course, in reality, no one does, except for the project owners (us). That's how most OSS projects "work". Sorry for not working full-time on this project over the holidays.

**Comment by giacomarco** [comment]
Thank you so much for your work and i'll do my best for help in this project. 
It's obviously that you don't work during holidays; holidays are made for refill "batteries"

**Comment by HackbrettXXX** [comment]
Fixed in #161.
