### ISSUE TITLE
Provide source map files or just remove the sourceMappingURL definition

### ISSUE THREAD

**Issue by scribetw** [yWorks/svg2pdf.js#125]
**Is your feature request related to a problem? Please describe.**
When I open Chrome dev tool, Chrome will request an `svg2pdf.js.map` file since a `sourceMappingURL` comment is presented.
But no source map is bundled with the js file.

**Describe the solution you'd like**
Provide `svg2pdf.js.map` and `svg2pdf.min.js.map` in dist folder.

**Describe alternatives you've considered**
Remove the source map definition in the js files
```js
//# sourceMappingURL=svg2pdf.js.map
```

**Additional context**
https://tracker.zkoss.org/browse/ZKCHARTS-104 our tracker

**Comment by HackbrettXXX** [comment]
Good point. We're probably going to fix this with the upcoming 2.0 release. We're currently quite occupied with other things, though, so this will take a while.

**Comment by HackbrettXXX** [comment]
Fixed with #119.
