### ISSUE TITLE
Incorrect rendering of svg on some attributes

### ISSUE THREAD

**Issue by arturasn** [yWorks/svg2pdf.js#130]
Some elements of the SVG are rendered incorrectly compared the html and pdf generated version of the svg2pdf.js 
I have made a jsFiddle to reproduce the errors: [link](https://jsfiddle.net/o6teqs1c/5/)
I expect the SVG in the pdf look the same as in html, however currently this is not the case.
Issues from what I see(maybe exists more):

1. Gradient is not used (I have played with this a little bit  and not ommiting default values(`x1="0%" y1="0%" x2="100%" y2="0%"`) seem to fix this however it should work regardless.
2. Vertical text incorrect positioning
3. Text and line in the center lifted up higher than expected

**Comment by HackbrettXXX** [comment]
Thank you for the bug report.

* Regarding the missing gradient: percentage values are generally not supported (with a few exceptions, see #82)
* Regarding the misplaced text: this seems to be an issue with the transform attribute or `rotate`. Maybe this is similar to #120?

**Comment by arturasn** [comment]
2) Vertical text incorrect positioning
3) Text and line in the center lifted up higher than expected

I see that with the newest version of svg2pdf.js(in online playground) the 2, 3 issues seem to be fixed. Will the percentage values be supported at any stage?

**Comment by HackbrettXXX** [comment]
Percentage values would be implemented in the context of #154. We currently don't plan to implement it on our own but we will merge pull requests from the community.

I'm closing this since 2 & 3 are fixed and 1 will be tracked by #154.
