### ISSUE TITLE
Incorrect PDF file dimensions after export.

### ISSUE THREAD

**Issue by Denyllon** [yWorks/svg2pdf.js#134]
**Describe the bug**
After setting the width and hight values of expected PDF file, getting the pdf where always a bigger value is taken as horizontal dimension.

**To Reproduce**
1. Open the example: https://jsfiddle.net/BlackLabel/168cukn4/
2. Look at the `width` and `height` values set before exporting
3. Open exported PDF file and look on its form (landscape).

**Expected behavior**
Exported PDF should always have dimensions equal to passed values

**Desktop (please complete the following information):**
 - OS: OSX 10.15.4
 - Browser: Chrome (Version 81.0.4044.113)
 - Version: 2.1.1

**Comment by HackbrettXXX** [comment]
That's in fact intended behavior, although if you ask me, the orientation parameter should be respected even if the dimensions don't match the orientation.

**Comment by Denyllon** [comment]
Didn't know the parameter which specifies orientation exists. You're right, closing the issue.
