### ISSUE TITLE
Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by psamim** [yWorks/svg2pdf.js#14]
Hi,
I get the following error:

```
Cannot read property 'toFixed' of undefined TypeError: Cannot read property 'toFixed' of undefined
at it (jspdf.min.js?01f5:29)
    at Rt.toString (jspdf.min.js?01f5:29)
    at dt (jspdf.min.js?01f5:29)
    at Zt (jspdf.min.js?01f5:29)
    at Object.<anonymous> (jspdf.min.js?01f5:29)
    at Object.Ut.t.foo [as output] (jspdf.min.js?01f5:29)
```
Thanks,
Samim

**Comment by yGuy** [comment]
Can you share a repro? At least the SVG you are trying to export. 
The stacktrace only contains jspdf and thus it may very well be a JSPDF issue.

**Comment by psamim** [comment]
@yGuy I am using `jspdf-yworks` as suggested.
This is my SVG below which is Highcharts chart.

https://gist.github.com/psamim/bbf2501d4291fdb24263b73ee597c720

**Comment by Vasilcenko** [comment]
I cannot reproduce your error. I simply replaced the svg in one of the textXX.html files with the one you provided and it worked for me.

Can you share a complete example where the error occurs?

**Comment by psamim** [comment]
I created  a repository https://github.com/psamim/svg2pdf.js-test
Just doing `npm install` and `./node_modules/.bin/webpack ./entry.js bundle.js` give the following error:

```
ERROR in ./~/svg2pdf.js/src/svg2pdf.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./rgbcolor in /home/samim/workspace/svg/node_modules/svg2pdf.js/src
 @ ./~/svg2pdf.js/src/svg2pdf.js 1446:4-1450:6

ERROR in ./~/svg2pdf.js/src/svg2pdf.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./SvgPath in /home/samim/workspace/svg/node_modules/svg2pdf.js/src
 @ ./~/svg2pdf.js/src/svg2pdf.js 1446:4-1450:6
```

**Comment by Vasilcenko** [comment]
Ok, several issues here:

- Our npm main entry was pointing to ./src instead of ./dist. I fixed that now and the fixed version is available as the v1.0.3 release. Update the dependency in your package.json, re-run `npm install` and you should be good t o go
- You have to also include _jspdf-yworks_ as a dependency in your package.json, as you are requiring it inside entry.js
- You should use the [raw-loader](https://www.npmjs.com/package/raw-loader) when requiring the svg file. So instead of `const svg = require('!file!./file.svg');` you write `const svg = require('!raw!./file.svg');`

I will create a PR for your repo.

Let me know if it works.

**Comment by psamim** [comment]
Thanks for quick replies and complete answers! I merged the pull request on my repo, I get the following error in the browser console.
```
Uncaught Error: Cannot find module "./rgbcolor"
    at webpackMissingModule (bundle.js:1913)
    at bundle.js:1913
    at Object.<anonymous> (bundle.js:1930)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:50)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:40
    at bundle.js:43
```

**Comment by Vasilcenko** [comment]
If I do a clean clone of your repository to an empty folder, then run `npm install` and then `./node_modules/.bin/webpack ./entry.js bundle.js`, then open the index.html I get no errors.
Can you provide further information about your setup? Which OS and browser are you using and what are the versions of your OS, browser and nodejs?

**Comment by psamim** [comment]
You are right, thanks anyway. The initial issue is somehow fixed now.
Thumbs up for your good support.
