### ISSUE TITLE
Custom font not work in svg2pdf

### ISSUE THREAD

**Issue by djae88** [yWorks/svg2pdf.js#146]
I tried really hard to solve this myself and search a lot Issues
I found many Issues about same problem but I couldn't find a solution after all

I refer to the documentation about custom fonts 
and make my font js file with https://rawgit.com/MrRio/jsPDF/master/fontconverter/fontconverter.html 
![image](https://user-images.githubusercontent.com/56290540/89427311-13694400-d776-11ea-8566-ae44c87b68d9.png)
and set my font too

![image](https://user-images.githubusercontent.com/56290540/89427365-224ff680-d776-11ea-9f85-fd1aa2c75164.png)

and the test was great
![image](https://user-images.githubusercontent.com/56290540/89427492-41e71f00-d776-11ea-96e9-356690958c9e.png)

but when I add svg with same text
![image](https://user-images.githubusercontent.com/56290540/89427657-73f88100-d776-11ea-8680-d13178f7d653.png)
![image](https://user-images.githubusercontent.com/56290540/89428086-f84b0400-d776-11ea-84a2-bca9e3704151.png)
![image](https://user-images.githubusercontent.com/56290540/89428013-dea9bc80-d776-11ea-8d18-820a218a3d3f.png)
This doesn't work...

I have no idea about this

#61 I found exactly same Issue too 
and he solved this, but he didn't offer a solution

What am I missing? I'm really desperate.
Even a small hint would be really appreciated.
Thanks

**Comment by yGuy** [comment]
A self-contained example is always easier to debug, but I believe all that you are missing is the font-family declaration at the SVG text element! 
Compare with the example, here: 
https://github.com/yWorks/svg2pdf.js/blob/14ebb1e2354f41cf68fef1379751a953a2030357/test/specs/custom-fonts/spec.svg#L2

**Comment by djae88** [comment]
Wow, Thank you very much for quick reply!
you saved my day :)
