### ISSUE TITLE
Support for css class tag in SVG

### ISSUE THREAD

**Issue by FHoffmannSopra** [yWorks/svg2pdf.js#162]
Hey guys,

I tried to render a ccs-styled polyline with the svg2pdf tool.

`<polyline points="125.5,112.55411200000003 125.5,142.55411200000003 125.5,212.62911200000002 126,212.62911200000002 126,282.704112 126,312.704112" fill="none" class="test"></polyline>`

Whenever I use a css-class the polyline is not rendered at all.
The css class is just a change to the color of the polyline, I wanted to make it as simple as possible.

I just need the info, if there is support for such statements at all, because in my case it is essential to use css classes to style my elements.

I am using svg2pdf 2.0.0 and jsPdf 2.0.0.

Thanks for your help
Frederic

**Comment by HackbrettXXX** [comment]
In theory, classes are supported. Where are your styles defined? svg2pdf supports SVG `style`, `link`, and `xml-stylesheet` tags. For `link` and `xml-stylesheet` tags you need to enable the [loadExternalStylesheets](https://github.com/yWorks/svg2pdf.js/blob/master/types.d.ts#L69) option. Note, that styles in the HTML of your webpage are not picked up. The styles need to be defined or referenced in the SVG itself.

**Comment by yGuy** [comment]
Works for me with my simple test:
[test it in Playground]( 
http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Cstyle%253E%250A%2520%2520%2520%2520.test%2520%257B%2520stroke%253A%2520blue%253B%2520stroke-width%253A%25205%2520%257D%250A%2520%2520%253C%252Fstyle%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%253EHello%252C%2520world%21%253C%252Ftext%253E%250A%2520%2520%253Cpolyline%2520class%253D%2522test%2522%2520fill%253D%2522none%2522%2520points%253D%252210%252010%252020%252020%252030%252010%252020%25200%2522%253E%253C%252Fpolyline%253E%250A%253C%252Fsvg%253E)

**Comment by FHoffmannSopra** [comment]
Thanks for your superfast reply. 

My styles are defined in a seperate css file, so they are not referenced in the Svg itself.
I guess that is the issue in my case.
So the key is to change the way I create the Svg.
