### ISSUE TITLE
Exported PDF content is empty / SVG not exported in PDF file

### ISSUE THREAD

**Issue by facuescobar** [yWorks/svg2pdf.js#169]
**Describe the bug**
The SVG content is not exported in PDF file

I'm able to generate the SVG content and display it as an HTML element in DOM. But When I export the PDF file, the SVG content is not included, the PDF content is empty.

**Code**
```javascript
const doc = new jsPDF() // eslint-disable-line

// Convert SVG string to HTML element
const svgWrapperElement = document.getElementById('svg-wrapper')
svgWrapperElement.innerHTML = window.toolSVG // SVG string located in window 
const svgElement = svgWrapperElement.firstChild

const svgOptions = {
    x: 0,
    y: 0,
    width: Number(svgElement.getAttribute('width')),
    height: Number(svgElement.getAttribute('height')),
}

doc.svg(svgElement, svgOptions).then(() => {
    doc.save('svg.pdf')
})
```

**Svg**
[http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=...](http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=%253Csvg%2520height%253D%2522633%2522%2520width%253D%25221178%2522%2520xmlns%253Axlink%253D%2522http%253A%252F%252Fwww.w3.org%252F1999%252Fxlink%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520version%253D%25221.1%2522%253E%253Cdefs%253E%253C%252Fdefs%253E%253Cg%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-width%253D%25222%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520355.734375%2520481.99999999999994%2520L%2520603%2520481.99999999999994%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522yellow%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-width%253D%25222%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520850.265625%2520481.99999999999994%2520L%2520603%2520481.99999999999994%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522yellow%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-width%253D%25222%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520603%2520481.99999999999994%2520L%2520603%2520234.73437499999997%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522yellow%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520355.734375%2520481.99999999999994%2520Q%2520405.1875%2520383.09374999999994%2520429.9140625%2520333.64062499999994%2520Q%2520454.640625%2520284.18749999999994%2520528.8203125%2520259.46093749999994%2520Q%2520603%2520234.73437499999997%2520677.1796875%2520259.46093749999994%2520Q%2520751.359375%2520284.18749999999994%2520776.0859375%2520333.64062499999994%2520Q%2520800.8125%2520383.09374999999994%2520850.265625%2520481.99999999999994%2520M%2520335.734375%2520481.99999999999994%2520Q%2520387.2989561800017%2520374.1494780900008%2520414.96979059000085%2520321.16848904500034%2520Q%2520442.640625%2520268.18749999999994%2520522.8203125%2520241.46093749999994%2520Q%2520603%2520214.73437499999997%2520683.1796875%2520241.46093749999994%2520Q%2520763.359375%2520268.18749999999994%2520791.0302094099991%2520321.16848904500034%2520Q%2520818.7010438199983%2520374.1494780900008%2520870.265625%2520481.99999999999994%2520M%2520335.734375%2520481.99999999999994%2520L%2520355.734375%2520481.99999999999994%2520M%2520870.265625%2520481.99999999999994%2520L%2520850.265625%2520481.99999999999994%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522red%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253C%252Fg%253E%253C%252Fsvg%253E) 

**Screenshots**
SVG Element in DOM
<img width="1180" alt="Screen Shot 2021-03-16 at 12 17 22 PM" src="https://user-images.githubusercontent.com/6618677/111334813-a5152a00-8652-11eb-9391-8772088486b6.png">

Exported PDF 
<img width="1157" alt="Screen Shot 2021-03-16 at 12 18 03 PM" src="https://user-images.githubusercontent.com/6618677/111334764-99c1fe80-8652-11eb-81f3-73a26e17629e.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome Version Version 88.0.4324

**Comment by yGuy** [comment]
Please post the SVG here: http://raw.githack.com/yWorks/svg2pdf.js/master/  as described in the issue template.
That's almost definitely a problem with the SVG and if you don't post it, we cannot help.
I could send you a PDF that *has* your shape, but that would not be helpful, either, or would it? ;-)

**Comment by facuescobar** [comment]
Thanks for your quick response @yGuy, sorry I've missed that part

Here's the [SVG](http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=%253Csvg%2520height%253D%2522633%2522%2520width%253D%25221178%2522%2520xmlns%253Axlink%253D%2522http%253A%252F%252Fwww.w3.org%252F1999%252Fxlink%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520version%253D%25221.1%2522%253E%253Cdefs%253E%253C%252Fdefs%253E%253Cg%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520NaN%2520NaN%2520A%252010%252010%25200%25201%25201%2520NaN%2520NaN%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522white%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-width%253D%25222%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520355.734375%2520481.99999999999994%2520L%2520603%2520481.99999999999994%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522yellow%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-width%253D%25222%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520850.265625%2520481.99999999999994%2520L%2520603%2520481.99999999999994%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522yellow%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-width%253D%25222%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520603%2520481.99999999999994%2520L%2520603%2520234.73437499999997%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522yellow%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253Cpath%2520stroke-dasharray%253D%2522%2522%2520stroke-miterlimit%253D%252210%2522%2520d%253D%2522M%2520355.734375%2520481.99999999999994%2520Q%2520405.1875%2520383.09374999999994%2520429.9140625%2520333.64062499999994%2520Q%2520454.640625%2520284.18749999999994%2520528.8203125%2520259.46093749999994%2520Q%2520603%2520234.73437499999997%2520677.1796875%2520259.46093749999994%2520Q%2520751.359375%2520284.18749999999994%2520776.0859375%2520333.64062499999994%2520Q%2520800.8125%2520383.09374999999994%2520850.265625%2520481.99999999999994%2520M%2520335.734375%2520481.99999999999994%2520Q%2520387.2989561800017%2520374.1494780900008%2520414.96979059000085%2520321.16848904500034%2520Q%2520442.640625%2520268.18749999999994%2520522.8203125%2520241.46093749999994%2520Q%2520603%2520214.73437499999997%2520683.1796875%2520241.46093749999994%2520Q%2520763.359375%2520268.18749999999994%2520791.0302094099991%2520321.16848904500034%2520Q%2520818.7010438199983%2520374.1494780900008%2520870.265625%2520481.99999999999994%2520M%2520335.734375%2520481.99999999999994%2520L%2520355.734375%2520481.99999999999994%2520M%2520870.265625%2520481.99999999999994%2520L%2520850.265625%2520481.99999999999994%2522%2520paint-order%253D%2522fill%2520stroke%2520markers%2522%2520stroke%253D%2522red%2522%2520fill%253D%2522none%2522%253E%253C%252Fpath%253E%253C%252Fg%253E%253C%252Fsvg%253E)

**Comment by yGuy** [comment]
Huh? But it does work in the link, doesn't it?
![image](https://user-images.githubusercontent.com/2486305/111337991-dacc0a00-8676-11eb-9653-8af85fb09b3f.png)

Please check how your code differs from our demo.

**Comment by facuescobar** [comment]
Yes, as you can see, the SVG works in the demo viewer, but it doesn't work in my code.

Do you think it could be a problem related to **svgOptions** or something?  I've tried exporting it without **svgOptions** but it doesn't work either.

**Comment by facuescobar** [comment]
Thanks for your suggestion @yGuy 

I've updated my code following the demo version, and the SVG is being exported now

```javascript
// Convert SVG string to HTML element
const svgWrapperElement = document.getElementById('svg-wrapper')
svgWrapperElement.innerHTML = window.chestWallToolSVG
const svgElement = svgWrapperElement.firstChild

// Force layout calculation
svgElement.getBoundingClientRect() 
const width = svgElement.width.baseVal.value
const height = svgElement.height.baseVal.value

// eslint-disable-next-line
const pdf = new jsPDF(width > height ? 'l' : 'p', 'pt', [
    width,
    height,
])

const svgOptions = { width, height }

pdf.svg(svgElement, svgOptions).then(() => {
    pdf.save('svg.pdf')
})
```
