### ISSUE TITLE
svg marker is not rendered

### ISSUE THREAD

**Issue by inu1255** [yWorks/svg2pdf.js#170]
**Describe the bug**
svg2pdf.js version 2.1.0

**To Reproduce**
[online playground](http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=%250A%253Csvg%2520xmlns%253Axlink%253D%2522http%253A%252F%252Fwww.w3.org%252F1999%252Fxlink%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520viewBox%253D%25220%25200%2520650%2520160%2522%2520height%253D%2522160%2522%2520width%253D%2522650%2522%2520version%253D%25221.1%2522%2520id%253D%2522kity_svg_12%2522%253E%250A%2509%253Cdefs%2520id%253D%2522kity_defs_13%2522%253E%250A%2509%2509%253Cmarker%2520markerUnits%253D%2522strokeWidth%2522%2520refY%253D%25222.5%2522%2520refX%253D%25225%2522%2520markerHeight%253D%25225%2522%2520markerWidth%253D%25225%2522%2520orient%253D%2522auto%2522%2520id%253D%2522kity_marker_105%2522%253E%250A%2509%2509%2509%253Cpath%2520stroke-width%253D%25220.3333333333333333%2522%2520d%253D%2522M0%252C0%2520L0%252C5%2520L5%252C2.5%2520Z%2522%2520stroke%253D%2522%25233982fc%2522%2520fill%253D%2522%2523fff%2522%2520id%253D%2522kity_path_106%2522%253E%253C%252Fpath%253E%250A%2509%2509%253C%252Fmarker%253E%250A%2509%253C%252Fdefs%253E%250A%2509%253Cg%2520id%253D%2522kity_g_14%2522%253E%250A%2509%2509%253Cg%2520transform%253D%2522translate%28%25200%2520100%2520%29%2522%2520text-rendering%253D%2522optimize-speed%2522%2520id%253D%2522minder1%2522%253E%250A%2509%2509%2509%253Cg%2520id%253D%2522minder_rel_line_group1%2522%253E%250A%2509%2509%2509%2509%253Cg%2520id%253D%2522minder_rel_line1%2522%253E%250A%2509%2509%2509%2509%2509%253Cpath%2520d%253D%2522M0%252C0M490.5%252C81C490.5%252C-26%252C13%252C-146.5%252C13%252C-30%2522%2520stroke-dasharray%253D%25226%252C3%2522%2520stroke-width%253D%25223%2522%2520marker-end%253D%2522url%28%2523kity_marker_105%29%2522%2520stroke%253D%2522%25233982fc%2522%2520fill%253D%2522none%2522%2520id%253D%2522kity_path_102%2522%253E%253C%252Fpath%253E%250A%2509%2509%2509%2509%2509%253Cpath%2520style%253D%2522cursor%253A%2520pointer%253B%2522%2520d%253D%2522M0%252C0M490.5%252C81C490.5%252C-26%252C13%252C-146.5%252C13%252C-30%2522%2520stroke-width%253D%25228%2522%2520stroke%253D%2522transparent%2522%2520fill%253D%2522none%2522%2520id%253D%2522kity_path_103%2522%253E%253C%252Fpath%253E%250A%2509%2509%2509%2509%253C%252Fg%253E%250A%2509%2509%2509%253C%252Fg%253E%250A%2509%2509%253C%252Fg%253E%250A%2509%253C%252Fg%253E%250A%253C%252Fsvg%253E%250A).

**Expected behavior**
marker rendered

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [89.0.4389.82]

**Comment by yGuy** [comment]
Thanks! I guess this is a known missing feature, but it's not listed in the known missing feature list :-/ 

No at least we have an issue for it.

**Comment by HackbrettXXX** [comment]
Markers are actually supported, but there are two bugs:

1. The `markerWidth` and `markerHeight` properties are not read correctly:
https://github.com/yWorks/svg2pdf.js/blob/d6dd5f105df37a6a4593dcddca6d22216a1a570d/src/nodes/marker.ts#L39-L40
should be
```
      (vb && vb[2]) || parseFloat(this.element.getAttribute('markerWidth') || '0'),
      (vb && vb[3]) || parseFloat(this.element.getAttribute('markerHeight') || '0')
```
2. The stroke-dasharray is inherited by the marker. We need to research how attributes are inherited from the user context to the marker.

**Comment by yGuy** [comment]
When we fix this, we should probably also check whether we should be using the `getAttribute` helper method, instead, to support CSS styling:
`getAttribute(this.element, context.styleSheets, 'markerWidth')

...and note that we do not support `markerUnits`

**Comment by HackbrettXXX** [comment]
`markerWidth/markerHeight` are not presentation attributes and cannot be set via CSS: https://svgwg.org/svg2-draft/styling.html#PresentationAttributes
