### ISSUE TITLE
Missing paths in SVG due to empty clip-path attribute

### ISSUE THREAD

**Issue by zornwal** [yWorks/svg2pdf.js#180]
**Describe the bug**
My SVG is missing paths when printing. They ought to be there and are rendered correctly in the playground SVG preview, but are also missing in the playground PDF preview.

jspdf@2.3.1
svg2pdf.js@2.1.0

**To Reproduce**
Use the [playground](http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=%253Csvg%2520version%253D%25221.1%2522%2520height%253D%2522198%2522%2520width%253D%2522198%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2509%253Cpath%2520style%253D%2522visibility%253A%2520visible%253B%2522%2520clip-path%253D%2522%2522%2520d%253D%2522M%25200%252065.175%2520L%252023.322683706070286%252062.7%2520L%252023.322683706070286%252062.7%2520L%252046.64536741214057%252052.800000000000004%2520L%252046.64536741214057%252052.800000000000004%2520L%252069.96805111821087%252051.15%2520L%252069.96805111821087%252051.15%2520L%252093.35463258785943%252037.949999999999996%2520L%252093.35463258785943%252037.949999999999996%2520L%2520116.67731629392972%252035.475%2520L%2520116.67731629392972%252035.475%2520L%2520140%252024.750000000000004%2522%2520stroke-dasharray%253D%25220%2522%2520stroke-width%253D%25222%2522%2520stroke%253D%2522%252300bdae%2522%2520fill%253D%2522none%2522%2520opacity%253D%25221%2522%2520id%253D%2522chart_57723_1_Series_0%2522%253E%250A%253C%252Fpath%253E%253C%252Fsvg%253E%250A%250A)

[(full svg)](https://github.com/yWorks/svg2pdf.js/files/6676778/example.txt)

**Expected behavior**
I would have expected the paths in the graph to be included.
I am aware that fonts need to be included in order to perfectly mirror the rendered svg.

**Screenshots**
![rendered svg (and expected pdf)](https://user-images.githubusercontent.com/22613687/122555924-31acfb00-d03b-11eb-9348-7cb4efa8ac8b.PNG)
![actual pdf](https://user-images.githubusercontent.com/22613687/122555926-32459180-d03b-11eb-9bcc-6d1b41ca72d9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 89

**Comment by HackbrettXXX** [comment]
Thanks for the issue report. Please try to reduce your SVG until only the missing path remains.

**Comment by zornwal** [comment]
Apologies, I have updated with a link to the playground with just the disappearing path.

**Comment by yGuy** [comment]
Obviously this is caused by the empty clippath attribute. Of course the workaround would be to remove it.

**Comment by zornwal** [comment]
If I remove the clip-path, the line will be visible through the nodes on the graph, though. If there is no other course of action, I will remove the nodes (and the clip-path).
Why is an empty clip-path an issue? (I know next to nothing about SVG)

**Comment by yGuy** [comment]
Well, this might be just a bug in svg2pdf, but as to why an empty-clip path might be an issue, you should ask the standard committee. 

Empty clip paths are not allowed and against the spec, I would say - use "none" (which is the default), if you don't need a clip path:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path  

I guess though, that you stripped-down the example a bit too much and that you still need a clip path and the original problem is another problem

**Comment by HackbrettXXX** [comment]
Seems to be a small bug in svg2pdf:

> An IRI reference to another graphical object within the same SVG document fragment which will be used as the clipping path. If the IRI reference is not valid (e.g it points to an object that doesn't exist or the object is not a ‘clipPath’ element) the ‘clip-path’ property must be treated as if it hadn't been specified.

**Comment by jagnathan** [comment]
hi @HackbrettXXX will this fix be included in the next release of svg2pdf? I am interested to know the date for the next release of svg2pdf. thanks

**Comment by HackbrettXXX** [comment]
@jagnathan yes it will be included in the next release but I can't tell you exactly when we will release it. Depends on the next release of jsPDF.
