### ISSUE TITLE
Use tag is working Please Help Me

### ISSUE THREAD

**Issue by neetu4567** [yWorks/svg2pdf.js#182]
![image](https://user-images.githubusercontent.com/71327619/124564456-b7fc7600-de5e-11eb-884a-803b31c9ef03.png)

**Comment by HackbrettXXX** [comment]
Please provide more information: what exactly is not working? How exactly can we reproduce the issue? Please also provide the SVG as text (or optimally a link to the playground with the SVG). Have you tested it outside the playground? Some features don't work on the playground for security reasons.
