### ISSUE TITLE
i need help please in pdf 

### ISSUE THREAD

**Issue by neetu4567** [yWorks/svg2pdf.js#183]
when i export pdf then open in corel draw its showing file is corrupted..

when i am export only single object then its working fine but when i am trying group of object by using "use tag" then its showing file is corrupted..

Please see screenshot below..

![image](https://user-images.githubusercontent.com/71327619/125034726-8e398e00-e0ae-11eb-9f98-ba7533f31935.png)

![image](https://user-images.githubusercontent.com/71327619/125034836-b6c18800-e0ae-11eb-9f74-89294504109f.png)

**Comment by yGuy** [comment]
Sorry, but I will need to block you from this project if you keep posting these useless questions. 
I fixed it for you:
![image](https://user-images.githubusercontent.com/2486305/125042354-05185c00-e09a-11eb-994a-c6bfea297b21.png)

Take your time and read through the instructions that we carefully crafted. Stick to them or stop wasting our time. Thanks.
