### ISSUE TITLE
Multiple SVG in 1 pdf support

### ISSUE THREAD

**Issue by jaimecigna** [yWorks/svg2pdf.js#193]
I am trying to use SVG2pdf to render multiple SVG's on 1 PDF.

Is this supported??

It doesn't seem to work when I try to use :
`pdf.svg()` inside of a forEach loop.

Any Help would be appreciated!

**Comment by HackbrettXXX** [comment]
That's probably because `pdf.svg()` is asynchronous. Use a for loop with await or something similar.

**Comment by jaimecigna** [comment]
good idea, i'll give a for loop a try. thanks for the suggestion

**Comment by jaimecigna** [comment]
> That's probably because `pdf.svg()` is asynchronous. Use a for loop with await or something similar.

Thanks for the suggestion, it worked!
