### ISSUE TITLE
Having issue in converting SVG to PDF --invalid argument to jsPDF.scale

### ISSUE THREAD

**Issue by im-hamza-dev** [yWorks/svg2pdf.js#210]
trying to add svg to pdf using jsPDF and svg2pdf but somehow got this exception:
![image](https://user-images.githubusercontent.com/32700351/165418937-8693c7a2-2a55-4056-8ed2-78b42190832d.png)

 let canvasWrapper = document.getElementById("svg-wrapper");
      canvasWrapper.innerHTML = jsonFile;

      canvasWrapper = canvasWrapper.firstChild;
      // canvasWrapper.getBoundingClientRect();
      const width = canvasWrapper.width?.baseVal?.value ?? 1200;
      const height = canvasWrapper.height?.baseVal?.value ?? 1000;

      console.log(canvasWrapper, canvasWrapper.width, canvasWrapper.height);
      // Generate PDF
      const pdf = new jsPDF(width > height ? "l" : "p", "pt", "a0");

      const svgOptions = { x: 0, y: 0, width, height };
      pdf.svg(canvasWrapper, svgOptions).then(() => {
        pdf.save("sv3432g.pdf");
      });

Need some suggestions on urgent basis!
Thanks

**Comment by HackbrettXXX** [comment]
Your code looks good, but the bug is probably caused by your SVG. Please provide a small SVG that reproduces the issue. Optimally, the issue can be reproduced in the [online playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html).

**Comment by im-hamza-dev** [comment]
here is the svg file:
![DryDock-1651003813](https://user-images.githubusercontent.com/32700351/165473702-60eca6d9-2f62-4265-b518-8598e26b3b4d.svg)

**Comment by HackbrettXXX** [comment]
That file is huge. Please try to reduce it to something manageable, optimally less than 10-20 tags/elements.

**Comment by FariJan** [comment]
http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Cg%2520style%253D%2522mix-blend-mode%253A%2520normal%2522%2520stroke-width%253D%2522none%2522%2520fill-rule%253D%2522nonzero%2522%2520fill%253D%2522none%2522%253E%250A%2520%2520%2520%2520%253Cpath%2520opacity%253D%25220.4%2522%2520stroke-width%253D%25223%2522%2520stroke%253D%2522%25237f7e7e%2522%2520fill%253D%2522%2523000000%2522%2520fill-opacity%253D%25220%2522%2520d%253D%2522M100.00003%252C100.00003h49.99995v49.99995h-49.99995z%2522%253E%253C%252Fpath%253E%250A%2520%2520%253C%252Fg%253E%2520%2520%250A%253C%252Fsvg%253E

`stroke-width="none"` causes this error

**Comment by yGuy** [comment]
I don't see that "none" is a valid value for the stroke-width attribute. Can you point me to the spec that tells what "none" should be? I guess you should simply be using "0" instead if you don't want a stroke or set the stroke itself to none? 

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width

**Comment by yGuy** [comment]
We are not going to implement a lenient parser that will try to make the best out of invalid or broken svg. Please fix the SVG or the tool that created the broken SVG.
