### ISSUE TITLE
PDF Mediabox Size | Outdated Limit

### ISSUE THREAD

**Issue by JacobAltar** [yWorks/svg2pdf.js#213]
In PDF Version 1.6 (Acrobat 7.0) and newer the theoretical PDF page size is 15,000,000"x15,000,000". 
svg2pdf.js is currently limited to 200" X 200". That does not cut it for large format banners.  

Please adjust the following...

(**n>14400**||o>**14400**)&&(i.warn("A page in a PDF can not be wider or taller than 14400 userUnit. jsPDF limits the width/height to 14400"),n=**Math.min(14400,n)**,o=**Math.min(14400,o)**)

**Comment by HackbrettXXX** [comment]
This is an issue in [jsPDF](https://github.com/parallax/jsPDF). Please create an issue there.
