### ISSUE TITLE
Add multiple SVG to PDF

### ISSUE THREAD

**Issue by iziorama** [yWorks/svg2pdf.js#216]
**Issue Description**
When I'm trying to add more then one svg to the .pdf document, all svg graphics placed on one page and it's elements occluding  and masking each other. As well it doesn't respect current page of the doc.

svg2pdf -2.2.0
jspdf – 2.5.1

**To Reproduce**
1. Add first svg to the pdf document using svg2pdf
2. Add page to the document with jspdf
3. Add second svg to the pdf document using svg2pdf 
4. In the resulted pdf document both svg graphics will be placed to the same page and occlude  

[Example link](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520width%253D%252250%2522%2520height%253D%252250%2522%2520viewBox%253D%25220%25200%2520100%2520100%2522%253E%250A%2520%2520%253Crect%2520width%253D%252250%2522%2520height%253D%252250%2522%2520fill%253D%2522red%2522%253E%253C%252Frect%253E%250A%2520%2520%253Ctext%2520x%253D%252210%2522%2520y%253D%252210%2522%253EHello%252C%2520world%21%253C%252Ftext%253E%250A%253C%252Fsvg%253E%250A%250A%253Csvg%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520width%253D%252250%2522%2520height%253D%252250%2522%2520viewBox%253D%25220%25200%2520100%2520100%2522%253E%250A%2520%2520%253Crect%2520width%253D%252250%2522%2520height%253D%252250%2522%2520fill%253D%2522green%2522%253E%253C%252Frect%253E%250A%2520%2520%253Ctext%2520x%253D%252220%2522%2520y%253D%252220%2522%253EGoodby%2520Worls%253C%252Ftext%253E%250A%253C%252Fsvg%253E)

**Expected behavior**
Graphics of the SVG should be added to the PDF document.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.17
 - Browser: Safari 
 - Version: 15.5

**Comment by yGuy** [comment]
The example link points to the playground which does not support adding multiple svgs and multiple pages.
Can you please update the example link to actually show the problem? There need to be multiple calls to  `pdf.svg()` in order for this to work.

**Comment by iziorama** [comment]
@yGuy when I'm tried to build example I've found the root cause of the issue. 
Function that contains `jsPdf` methods should be **async** and all `pdf.svg()` should have **await** keyword.

Here is the working example:
https://jsfiddle.net/iziorama/w2t0po5e/93/
