### ISSUE TITLE
When font-size declared in rem, text is missing in the exported file.

### ISSUE THREAD

**Issue by karolkolodziej** [yWorks/svg2pdf.js#232]
**Describe the bug**
When adding the `font-size` expressed in `rem` to a text, it is not visible in the exported file.

**To Reproduce**
See this [playground](https://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%2520style%253D%2522font-size%253A%25203rem%253B%2522%253EHello%252C%2520world%21%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

**Expected behavior**
The `font-size` in `rem` should be applied similarly to the on in `px`- which works well.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Browser: Chrome
 - Version: 106.0.5249.91 (Official Build) (arm64)

**Comment by yGuy** [comment]
Not sure whether "rem" is officially supported in SVGs, not even SVG2 seems to be clear on this: https://svgwg.org/svg2-draft/types.html#InterfaceSVGLength

And I don't think browsers, agree with the implementation, either: https://bugzilla.mozilla.org/show_bug.cgi?id=1231147

How should the size be determined for an SVG embedded into a PDF? Font sizes relative to *what*?

**Comment by karolkolodziej** [comment]
> How should the size be determined for an SVG embedded into a PDF? Font sizes relative to what?

I guess it should work similarly to the `em` only being relative to the top element - [demo](https://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%2520style%253D%2522font-size%253A%25203em%253B%2522%253EHello%252C%2520world%21%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

Indeed the SVG2 documention doesn't mention the `rem`.
 However percentages are there and they also don't work correctly- [demo](https://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%2520style%253D%2522font-size%253A%252070%2525%253B%2522%253EHello%252C%2520world%21%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

**Comment by yGuy** [comment]
Let's create another issue for the `em` case. 
I am closing this for the "rem" case until there is a spec for this available. I don't see that this can be an important use-case as long as it only works inside the HTML DOM in a browser.
