### ISSUE TITLE
Marker clipping

### ISSUE THREAD

**Issue by edemaine** [yWorks/svg2pdf.js#245]
**Describe the bug**
Used `<marker>`s get clipped by a weird rectangle.

**To Reproduce**
Put the following into a .html file, then open in a web browser. (Warning: It will immediately trigger a download of file test.pdf)

```html
<html>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="117.63845825195312 182.9512939453125 48.78462219238281 84.23074340820312" width="48.78462219238281px" height="84.23074340820312px">
<marker id="arrow-black" viewBox="0 0 10 10" refX="9.5" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse" overflow="visible"><path d="M 0 -1 L 10 3.854 A 1.252 1.252 0 0 1 10 6.146 L 0 11 z" fill="black"/></marker>
<polyline data-id="t8LpCW5Bm3bokNtgs" points="119.13845825195312,265.6820373535156 164.92308044433594,184.4512939453125" stroke="black" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" fill="none" marker-end="url(#arrow-black)"/>
</svg>
<script type="module">
const {jsPDF} = await import("https://cdn.skypack.dev/pin/jspdf@v2.5.0-qOUBjLwjpjtUHvljumfc/dist=es2020,mode=imports,min/optimized/jspdf.js")
const {svg2pdf} = await import("https://cdn.skypack.dev/pin/svg2pdf.js@v2.2.1-E39EA3q6JjbAU0rSktv0/mode=imports,min/optimized/svg2pdfjs.js")
const width = 48.78462219238281
const height = 84.23074340820312
const pdf = new jsPDF({format: [width, height], orientation: 'portrait'})
await svg2pdf(document.querySelector('svg'), pdf, {width, height})
pdf.save('test.pdf')
</script>
</html>
```

**Expected behavior**
It should look like the SVG:

![image](https://user-images.githubusercontent.com/2218736/208178094-a8616114-2356-4211-8b3f-bdaa6da20181.png)

**Screenshots**
Instead the marker gets clipped.  Here's a screenshot in Illustrator:

![image](https://user-images.githubusercontent.com/2218736/208177710-15d9b01b-67cf-43f2-bf7b-2bd689d5b93b.png)

[In the playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520height%253D%252284.23074340820312px%2522%2520width%253D%252248.78462219238281px%2522%2520viewBox%253D%2522117.63845825195312%2520182.9512939453125%252048.78462219238281%252084.23074340820312%2522%2520xmlns%253Axlink%253D%2522http%253A%252F%252Fwww.w3.org%252F1999%252Fxlink%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%253Cmarker%2520overflow%253D%2522visible%2522%2520orient%253D%2522auto-start-reverse%2522%2520markerHeight%253D%25224%2522%2520markerWidth%253D%25224%2522%2520refY%253D%25225%2522%2520refX%253D%25229.5%2522%2520viewBox%253D%25220%25200%252010%252010%2522%2520id%253D%2522arrow-black%2522%253E%253Cpath%2520fill%253D%2522black%2522%2520d%253D%2522M%25200%2520-1%2520L%252010%25203.854%2520A%25201.252%25201.252%25200%25200%25201%252010%25206.146%2520L%25200%252011%2520z%2522%253E%253C%252Fpath%253E%253C%252Fmarker%253E%250A%253Cpolyline%2520marker-end%253D%2522url%28%2523arrow-black%29%2522%2520fill%253D%2522none%2522%2520stroke-linejoin%253D%2522round%2522%2520stroke-linecap%253D%2522round%2522%2520stroke-width%253D%25223%2522%2520stroke%253D%2522black%2522%2520points%253D%2522119.13845825195312%252C265.6820373535156%2520164.92308044433594%252C184.4512939453125%2522%2520data-id%253D%2522t8LpCW5Bm3bokNtgs%2522%253E%253C%252Fpolyline%253E%250A%253C%252Fsvg%253E) it's much better, but the back corners of the marker are clipped a little:

![image](https://user-images.githubusercontent.com/2218736/208177808-9e3c2e6d-ffe4-436b-9894-0455764c749a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
- Browser: Chrome
- Version: 108.0.5359.100

**Comment by yGuy** [comment]
Looks like the viewbox is very tight around the arrow and maybe the path thickness is not considered for the clip. Obviously even Illustrator and Chrome's PDF rendering engine disagree, here.

Maybe, as a workaround try to increase the viewbox of the marker:

[Playground variation](https://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520xmlns%253Axlink%253D%2522http%253A%252F%252Fwww.w3.org%252F1999%252Fxlink%2522%2520viewBox%253D%2522117.63845825195312%2520182.9512939453125%252048.78462219238281%252084.23074340820312%2522%2520width%253D%252248.78462219238281px%2522%2520height%253D%252284.23074340820312px%2522%253E%250A%253Cmarker%2520id%253D%2522arrow-black%2522%2520viewBox%253D%2522-2%2520-2%252012%252014%2522%2520refX%253D%25229.5%2522%2520refY%253D%25225%2522%2520markerWidth%253D%25224%2522%2520markerHeight%253D%25224%2522%2520orient%253D%2522auto-start-reverse%2522%2520overflow%253D%2522visible%2522%253E%253Cpath%2520d%253D%2522M%25200%2520-1%2520L%252010%25203.854%2520A%25201.252%25201.252%25200%25200%25201%252010%25206.146%2520L%25200%252011%2520z%2522%2520fill%253D%2522black%2522%253E%253C%252Fpath%253E%253C%252Fmarker%253E%250A%253Cpolyline%2520data-id%253D%2522t8LpCW5Bm3bokNtgs%2522%2520points%253D%2522119.13845825195312%252C265.6820373535156%2520164.92308044433594%252C184.4512939453125%2522%2520stroke%253D%2522black%2522%2520stroke-width%253D%25223%2522%2520stroke-linecap%253D%2522round%2522%2520stroke-linejoin%253D%2522round%2522%2520fill%253D%2522none%2522%2520marker-end%253D%2522url%28%2523arrow-black%29%2522%253E%253C%252Fpolyline%253E%250A%253C%252Fsvg%253E)

**Comment by edemaine** [comment]
Adding `unit: 'px'` to the `jsPDF` constructor, as suggested in https://github.com/yWorks/svg2pdf.js/issues/244#issuecomment-1670984841 , fixed this issue as well. Closing in favor of https://github.com/parallax/jsPDF/issues/3627
