### ISSUE TITLE
Custom font usage

### ISSUE THREAD

**Issue by phyzalis** [yWorks/svg2pdf.js#25]
Hi

Is there anyway to add custom font in pdf generation?

I have a custom font in my svg included with a def like this:

    <defs>
      <style type="text/css">
        @import url(http://fonts.googleapis.com/css?family=Indie+Flower);
      </style>
    </defs>

Everything is fine in my svg, but when I convert to pdf, the default font is used.
Anything about this?

Many thanks

**Comment by yGuy** [comment]
That's actually a [JSPDF issue](https://github.com/MrRio/jsPDF/issues/115). 

There is one project that tries to solve this: https://github.com/sphilee/jsPDF-CustomFonts-support

This cannot and should not be fixed in svg2pdf.
