### ISSUE TITLE
Black background added to paths

### ISSUE THREAD

**Issue by infinitemind2** [yWorks/svg2pdf.js#253]
**Describe the bug**
What version are you using (exact version of svg2pdf.js and jspdf)?

jspdf - 2.5.1
svg2pad - 2.2.1

**To Reproduce**
1. With the following SVG code from produced page

<svg width="926.99658203125" height="500" style="overflow: hidden; display: block;"><defs><clipPath id="bb-773992782612126-clip"><rect width="884.99658203125" height="446"></rect></clipPath><clipPath id="bb-773992782612126-clip-xaxis"><rect x="-19" y="-15" width="914.99658203125" height="70"></rect></clipPath><clipPath id="bb-773992782612126-clip-yaxis"><rect x="-39" y="-4" width="60" height="460"></rect></clipPath><clipPath id="bb-773992782612126-clip-grid"><rect width="884.99658203125" height="446"></rect></clipPath></defs><g class="bb-main" transform="translate(40.5, 4.5)"><g clip-path="url(http://localhost:8088/qld-future-climate/reports#bb-773992782612126-clip-grid)" class="bb-grid"><g class="bb-xgrid-focus"><line class="bb-xgrid-focus" x1="183" x2="183" y2="446" style="visibility: hidden;" y1="0"></line></g></g><g class="bb-chart" clip-path="url(http://localhost:8088/qld-future-climate/reports#bb-773992782612126-clip)"><g class="bb-event-rects bb-event-rects-single" style="fill-opacity: 0;"><rect x="0" y="0" width="884.99658203125" height="446" class="bb-event-rect"></rect></g><g class="bb-chart-lines"><g class="bb-chart-line bb-target bb-target-data1  " style="pointer-events: none;"><g class="bb-shapes bb-shapes-data1 bb-lines bb-lines-data1"><path class="bb-shape bb-shape bb-line bb-line-data1 " d="M9,332.72727272727275L183,340.81818181818187L356,336.77272727272725L530,348.9090909090909L703,324.6363636363636L877,316.54545454545456" style="stroke: rgb(31, 119, 180);"></path></g><g class="bb-shapes bb-shapes-data1 bb-areas bb-areas-data1"><path class="bb-shape bb-shape bb-area bb-area-data1" d="M9,357L183,352.95454545454544L356,348.9090909090909L530,357L703,340.81818181818187L877,344.8636363636364L877,284.9909090909091L703,300.3636363636364L530,336.77272727272725L356,316.54545454545456L183,320.5909090909092L9,324.6363636363636Z" style="fill: rgb(31, 119, 180); opacity: 0.114286;"></path></g><g class="bb-shapes bb-shapes-data1 bb-circles bb-circles-data1"><circle class="bb-shape bb-shape-0 bb-circle bb-circle-0" r="2.5" cx="9" cy="332.72727272727275" style="fill: rgb(31, 119, 180); stroke: rgb(31, 119, 180);"></circle><circle class="bb-shape bb-shape-1 bb-circle bb-circle-1" r="2.5" cx="183" cy="340.81818181818187" style="fill: rgb(31, 119, 180); stroke: rgb(31, 119, 180);"></circle><circle class="bb-shape bb-shape-2 bb-circle bb-circle-2" r="2.5" cx="356" cy="336.77272727272725" style="fill: rgb(31, 119, 180); stroke: rgb(31, 119, 180);"></circle><circle class="bb-shape bb-shape-3 bb-circle bb-circle-3" r="2.5" cx="530" cy="348.9090909090909" style="fill: rgb(31, 119, 180); stroke: rgb(31, 119, 180);"></circle><circle class="bb-shape bb-shape-4 bb-circle bb-circle-4" r="2.5" cx="703" cy="324.6363636363636" style="fill: rgb(31, 119, 180); stroke: rgb(31, 119, 180);"></circle><circle class="bb-shape bb-shape-5 bb-circle bb-circle-5" r="2.5" cx="877" cy="316.54545454545456" style="fill: rgb(31, 119, 180); stroke: rgb(31, 119, 180);"></circle></g></g><g class="bb-chart-line bb-target bb-target-data2  " style="pointer-events: none;"><g class="bb-shapes bb-shapes-data2 bb-lines bb-lines-data2"><path class="bb-shape bb-shape bb-line bb-line-data2 " d="M9,340.81818181818187L183,170.90909090909093L356,284.1818181818182L530,41.45454545454547L703,243.72727272727272L877,162.8181818181818" style="stroke: rgb(255, 127, 14);"></path></g><g class="bb-shapes bb-shapes-data2 bb-circles bb-circles-data2"><circle class="bb-shape bb-shape-0 bb-circle bb-circle-0" r="2.5" cx="9" cy="340.81818181818187" style="fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle><circle class="bb-shape bb-shape-1 bb-circle bb-circle-1" r="2.5" cx="183" cy="170.90909090909093" style="fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle><circle class="bb-shape bb-shape-2 bb-circle bb-circle-2" r="2.5" cx="356" cy="284.1818181818182" style="fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle><circle class="bb-shape bb-shape-3 bb-circle bb-circle-3" r="2.5" cx="530" cy="41.45454545454547" style="fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle><circle class="bb-shape bb-shape-4 bb-circle bb-circle-4" r="2.5" cx="703" cy="243.72727272727272" style="fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle><circle class="bb-shape bb-shape-5 bb-circle bb-circle-5" r="2.5" cx="877" cy="162.8181818181818" style="fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle></g></g><g class="bb-chart-line bb-target bb-target-data3  " style="pointer-events: none;"><g class="bb-shapes bb-shapes-data3 bb-lines bb-lines-data3"><path class="bb-shape bb-shape bb-line bb-line-data3 " d="M9,272.04545454545456C9,272.04545454545456,125.16666666666667,266.6515151515151,183,263.95454545454544C240.83333333333331,261.25757575757575,298.1666666666667,258.56060606060606,356,255.86363636363637C413.8333333333333,253.16666666666669,472.1666666666667,250.46969696969697,530,247.77272727272728C587.8333333333334,245.0757575757576,645.1666666666666,236.9848484848485,703,239.6818181818182C760.8333333333334,242.37878787878788,877,263.95454545454544,877,263.95454545454544" style="stroke: rgb(44, 160, 44);"></path></g><g class="bb-shapes bb-shapes-data3 bb-areas bb-areas-data3"><path class="bb-shape bb-shape bb-area bb-area-data3" d="M9,280.1363636363636C9,280.1363636363636,125.16666666666667,274.74242424242425,183,272.04545454545456C240.83333333333331,269.3484848484849,298.1666666666667,266.6515151515151,356,263.95454545454544C413.8333333333333,261.25757575757575,472.1666666666667,255.86363636363637,530,255.86363636363637C587.8333333333334,255.86363636363637,645.1666666666666,261.25757575757575,703,263.95454545454544C760.8333333333334,266.6515151515151,877,272.04545454545456,877,272.04545454545456L877,251.81818181818184C877,251.81818181818184,760.8333333333334,232.93939393939394,703,227.54545454545453C645.1666666666666,222.15151515151513,587.8333333333334,218.10606060606062,530,219.45454545454547C472.1666666666667,220.8030303030303,413.8333333333333,230.24242424242425,356,235.63636363636365C298.1666666666667,241.03030303030306,240.83333333333331,246.42424242424246,183,251.81818181818184C125.16666666666667,257.21212121212125,9,267.99999999999994,9,267.99999999999994Z" style="fill: rgb(44, 160, 44); opacity: 0.114286;"></path></g><g class="bb-shapes bb-shapes-data3 bb-circles bb-circles-data3"><circle class="bb-shape bb-shape-0 bb-circle bb-circle-0" r="2.5" cx="9" cy="272.04545454545456" style="fill: rgb(44, 160, 44); stroke: rgb(44, 160, 44);"></circle><circle class="bb-shape bb-shape-1 bb-circle bb-circle-1" r="2.5" cx="183" cy="263.95454545454544" style="fill: rgb(44, 160, 44); stroke: rgb(44, 160, 44);"></circle><circle class="bb-shape bb-shape-2 bb-circle bb-circle-2" r="2.5" cx="356" cy="255.86363636363637" style="fill: rgb(44, 160, 44); stroke: rgb(44, 160, 44);"></circle><circle class="bb-shape bb-shape-3 bb-circle bb-circle-3" r="2.5" cx="530" cy="247.77272727272728" style="fill: rgb(44, 160, 44); stroke: rgb(44, 160, 44);"></circle><circle class="bb-shape bb-shape-4 bb-circle bb-circle-4" r="2.5" cx="703" cy="239.6818181818182" style="fill: rgb(44, 160, 44); stroke: rgb(44, 160, 44);"></circle><circle class="bb-shape bb-shape-5 bb-circle bb-circle-5" r="2.5" cx="877" cy="263.95454545454544" style="fill: rgb(44, 160, 44); stroke: rgb(44, 160, 44);"></circle></g></g><g class="bb-chart-line bb-target bb-target-data4" style="pointer-events: none;"><g class="bb-shapes bb-shapes-data4 bb-lines bb-lines-data4"><path class="bb-shape bb-shape bb-line bb-line-data4 " d="M9,324.6363636363636C9,324.6363636363636,125.16666666666667,301.0378787878788,183,292.2727272727273C240.83333333333331,283.5075757575758,298.1666666666667,273.39393939393943,356,272.04545454545456C413.8333333333333,270.6969696969697,472.1666666666667,283.50757575757575,530,284.1818181818182C587.8333333333334,284.8560606060606,645.1666666666666,273.3939393939394,703,276.09090909090907C760.8333333333334,278.78787878787875,877,300.3636363636364,877,300.3636363636364" style="stroke: rgb(214, 39, 40);"></path></g><g class="bb-shapes bb-shapes-data4 bb-areas bb-areas-data4"><path class="bb-shape bb-shape bb-area bb-area-data4" d="M9,328.68181818181813C9,328.68181818181813,125.16666666666667,332.05303030303025,183,324.6363636363636C240.83333333333331,317.219696969697,298.1666666666667,288.22727272727275,356,284.1818181818182C413.8333333333333,280.1363636363636,472.1666666666667,299.0151515151515,530,300.3636363636364C587.8333333333334,301.71212121212125,645.1666666666666,289.5757575757576,703,292.2727272727273C760.8333333333334,294.969696969697,877,316.54545454545456,877,316.54545454545456L877,284.1818181818182C877,284.1818181818182,760.8333333333334,269.3484848484848,703,267.99999999999994C645.1666666666666,266.65151515151507,587.8333333333334,277.4393939393939,530,276.09090909090907C472.1666666666667,274.74242424242425,413.8333333333333,258.56060606060606,356,259.90909090909093C298.1666666666667,261.2575757575758,240.83333333333331,274.0681818181818,183,284.1818181818182C125.16666666666667,294.29545454545456,9,320.5909090909092,9,320.5909090909092Z" style="fill: rgb(214, 39, 40); opacity: 0.114286;"></path></g><g class="bb-shapes bb-shapes-data4 bb-circles bb-circles-data4"><circle class="bb-shape bb-shape-0 bb-circle bb-circle-0" r="2.5" cx="9" cy="324.6363636363636" style="fill: rgb(214, 39, 40); stroke: rgb(214, 39, 40);"></circle><circle class="bb-shape bb-shape-1 bb-circle bb-circle-1" r="2.5" cx="183" cy="292.2727272727273" style="fill: rgb(214, 39, 40); stroke: rgb(214, 39, 40);"></circle><circle class="bb-shape bb-shape-2 bb-circle bb-circle-2" r="2.5" cx="356" cy="272.04545454545456" style="fill: rgb(214, 39, 40); stroke: rgb(214, 39, 40);"></circle><circle class="bb-shape bb-shape-3 bb-circle bb-circle-3" r="2.5" cx="530" cy="284.1818181818182" style="fill: rgb(214, 39, 40); stroke: rgb(214, 39, 40);"></circle><circle class="bb-shape bb-shape-4 bb-circle bb-circle-4" r="2.5" cx="703" cy="276.09090909090907" style="fill: rgb(214, 39, 40); stroke: rgb(214, 39, 40);"></circle><circle class="bb-shape bb-shape-5 bb-circle bb-circle-5" r="2.5" cx="877" cy="300.3636363636364" style="fill: rgb(214, 39, 40); stroke: rgb(214, 39, 40);"></circle></g></g></g></g><g class="bb-axis bb-axis-x" clip-path="url(http://localhost:8088/qld-future-climate/reports#bb-773992782612126-clip-xaxis)" transform="translate(0, 446)"><text class="bb-axis-x-label" style="text-anchor: end;" x="884.99658203125" dx="-0.5em" dy="-0.5em"></text><g class="tick" transform="translate(9,0)"><line x2="0" x1="0" y2="6"></line><text x="0" y="9" style="text-anchor: middle;"><tspan x="0" dx="0" dy=".71em">2013-01-01</tspan></text></g><g class="tick" transform="translate(183,0)"><line x2="0" x1="0" y2="6"></line><text x="0" y="9" style="text-anchor: middle;"><tspan x="0" dx="0" dy=".71em">2013-01-02</tspan></text></g><g class="tick" transform="translate(356,0)"><line x2="0" x1="0" y2="6"></line><text x="0" y="9" style="text-anchor: middle;"><tspan x="0" dx="0" dy=".71em">2013-01-03</tspan></text></g><g class="tick" transform="translate(530,0)"><line x2="0" x1="0" y2="6"></line><text x="0" y="9" style="text-anchor: middle;"><tspan x="0" dx="0" dy=".71em">2013-01-04</tspan></text></g><g class="tick" transform="translate(703,0)"><line x2="0" x1="0" y2="6"></line><text x="0" y="9" style="text-anchor: middle;"><tspan x="0" dx="0" dy=".71em">2013-01-05</tspan></text></g><g class="tick" transform="translate(877,0)"><line x2="0" x1="0" y2="6"></line><text x="0" y="9" style="text-anchor: middle;"><tspan x="0" dx="0" dy=".71em">2013-01-06</tspan></text></g><path class="domain" d="M0,6V0H884.99658203125V6"></path></g><g class="bb-axis bb-axis-y" clip-path="url(http://localhost:8088/qld-future-climate/reports#bb-773992782612126-clip-yaxis)" transform="translate(0, 0)"><text class="bb-axis-y-label" transform="rotate(-90)" style="text-anchor: end;" x="0" dx="-0.5em" dy="1.2em"></text><g class="tick" transform="translate(0,446)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">0</tspan></text></g><g class="tick" transform="translate(0,406)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">50</tspan></text></g><g class="tick" transform="translate(0,366)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">100</tspan></text></g><g class="tick" transform="translate(0,325)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">150</tspan></text></g><g class="tick" transform="translate(0,285)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">200</tspan></text></g><g class="tick" transform="translate(0,244)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">250</tspan></text></g><g class="tick" transform="translate(0,204)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">300</tspan></text></g><g class="tick" transform="translate(0,163)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">350</tspan></text></g><g class="tick" transform="translate(0,123)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">400</tspan></text></g><g class="tick" transform="translate(0,82)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">450</tspan></text></g><g class="tick" transform="translate(0,42)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">500</tspan></text></g><g class="tick" transform="translate(0,1)"><line x2="-6" y1="0" y2="0"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dx="0" dy="3">550</tspan></text></g><path class="domain" d="M-6,1H0V446H-6"></path></g></g><g class="bb-legend" transform="translate(0, 480)"><g class="bb-legend-item bb-legend-item-data1" style="cursor: pointer;"><text x="371.91645336151123" y="9" style="pointer-events: none;">data1</text><rect class="bb-legend-item-event" x="357.91645336151123" y="-5" width="55.01736259460449" height="17.33333396911621" style="fill-opacity: 0;"></rect><line class="bb-legend-item-tile" stroke-width="10" x1="355.91645336151123" y1="4" x2="365.91645336151123" y2="4" style="stroke: rgb(31, 119, 180); pointer-events: none;"></line></g><g class="bb-legend-item bb-legend-item-data2" style="cursor: pointer;"><text x="426.9338159561157" y="9" style="pointer-events: none;">data2</text><rect class="bb-legend-item-event" x="412.9338159561157" y="-5" width="55.01736259460449" height="17.33333396911621" style="fill-opacity: 0;"></rect><line class="bb-legend-item-tile" stroke-width="10" x1="410.9338159561157" y1="4" x2="420.9338159561157" y2="4" style="stroke: rgb(255, 127, 14); pointer-events: none;"></line></g><g class="bb-legend-item bb-legend-item-data3" style="cursor: pointer;"><text x="481.9511785507202" y="9" style="pointer-events: none;">data3</text><rect class="bb-legend-item-event" x="467.9511785507202" y="-5" style="fill-opacity: 0;" width="55.01736259460449" height="17.33333396911621"></rect><line class="bb-legend-item-tile" stroke-width="10" x1="465.9511785507202" y1="4" x2="475.9511785507202" y2="4" style="stroke: rgb(44, 160, 44); pointer-events: none;"></line></g><g class="bb-legend-item bb-legend-item-data4" style="cursor: pointer;"><text x="536.9685411453247" y="9" style="pointer-events: none;">data4</text><rect class="bb-legend-item-event" x="522.9685411453247" y="-5" style="fill-opacity: 0;" width="46.11158752441406" height="17.33333396911621"></rect><line class="bb-legend-item-tile" stroke-width="10" x1="520.9685411453247" y1="4" x2="530.9685411453247" y2="4" style="stroke: rgb(214, 39, 40); pointer-events: none;"></line></g></g></svg>

2. I get this result

![image](https://user-images.githubusercontent.com/1028742/216229711-518189b4-abc4-4e0a-9cf3-39e0f444558c.png)

E.g. provide a link to the [online playground](http://raw.githack.com/yWorks/svg2pdf.js/master/).

**Expected behavior**
I would have expected the PDF to look like so. 

![image](https://user-images.githubusercontent.com/1028742/216229908-5cbcf0ca-c464-44e6-ae94-8d1d9e7ba587.png)

Extra line placed with a black background, can I just add a path specification in the css to remove?

This is in accordance to the following SVG spec

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: chrome
 - Version: 108.0.5359.72

**Additional context**

**Comment by yGuy** [comment]
I wouldn't exactly call this SVG code:

> With the following SVG code from produced page
2013-01-012013-01-022013-01-032013-01-042013-01-052013-01-06050100150200250300350400450500550data1data2data3data4

We need a proper repro, here.

**Comment by infinitemind2** [comment]
![code](https://user-images.githubusercontent.com/1028742/216465974-6a7ded73-df9b-4472-ac5b-d45c16462a61.svg)

Fixed the problem by including the css file contents into the defs section of the svg. the file above is the fixed version and works a treat now. 

Sometimes I just need a prod and a nights sleep to figure things out. 

Thanks

**Comment by infinitemind2** [comment]
the svg code works in your playground.
However when I run through my code, no luck. Does not seem to recognise the new css in the CDATA section

`
function SavePDFFile(props, width, height) {
            
                var svg = document.getElementById("reportbox").children[0];

                svg.getBoundingClientRect() // force layout calculation
                const w = svg.width.baseVal.value
                const h = svg.height.baseVal.value
        
                svg.setAttribute('viewBox','0 0 '+ w +' '+ h);
                svg.setAttribute('xmlns:xlink','http://www.w3.org/1999/xlink');
                svg.setAttribute('xmlns','http://www.w3.org/2000/svg');
        
                $.get('/app-data/graphcss.txt', function (resp) {
                    // resp now should contain your CSS file content.
                    var def = Object.assign(document.createElement('style'), {textContent: resp});
                    def.setAttribute('type','text/css');

                    svg.children[0].prepend(def);
                    
                    const doc = new jspdf.jsPDF(w > h ? 'l' : 'p', 'pt', [w, h])
              
                    doc.svg(svg, { w, h }).then(function(pdf) {
                            // Save the PDF
                            pdf.save('document-svg.pdf');
                            
                    });
                });
        }
`

**Comment by yGuy** [comment]
Your code does not seem to wait for the CSS to actually load. Creating the style element will not synchronously load and apply the CSS. Please come up with a minimal executable repro if you think this is an issue with svg2pdf. From the code above, I think the issue is a timing issue with the CSS loading.

**Comment by infinitemind2** [comment]
How do you wait for CSS to load. Just putting together a basic page with the graph.

**Comment by infinitemind2** [comment]
This produces the same results as above
[graphcss.txt](https://github.com/yWorks/svg2pdf.js/files/10670317/graphcss.txt)
[graphdemo.html.txt](https://github.com/yWorks/svg2pdf.js/files/10670323/graphdemo.html.txt)

**Comment by yGuy** [comment]
Works for me: https://jsfiddle.net/o6sv8bdh/

Please modify the fiddle and strip it down if you're still having problems.

You will get a lot more help on GitHub if you come up with minimal repros. Typically most people do not want to wade through tons of unrelated sources and your requests will be ignored instead. Thanks.

**Comment by infinitemind2** [comment]
Sebastian,

Thanks for your help.
The fiddle you set up works, noticed that you removed the CDATA tags from the css insertion into the svg element (which I thought was required). Did the same and all worked perfectly as expected within my page.

David
