### ISSUE TITLE
Chinese is not supported

### ISSUE THREAD

**Issue by hhly** [yWorks/svg2pdf.js#254]
**Describe the bug**

**To Reproduce**
See this [playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%253E%25E4%25BD%25A0%25E5%25A5%25BD%25E5%2595%258A%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

**Expected behavior**
I would have expected the PDF to look like so. 
This is in accordance to the following SVG spec.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hhly** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/29226405/221128193-8c773787-18e9-4376-8fab-ff7717d4d42c.png">
I added fonts, but Chinese is still garbled

**Comment by yGuy** [comment]
Works for me

![image](https://user-images.githubusercontent.com/2486305/221356376-05ec1d19-1e38-44de-8e54-878a2983a92a.png)

The playground doesn't have a font with chinese characters loaded, but your SVG failed to specify the font name, anyway. You need to specify the font name in the SVG, too.
