### ISSUE TITLE
How to ignore invalid dataurl 

### ISSUE THREAD

**Issue by tangenttechno** [yWorks/svg2pdf.js#262]
I am using Apache PDFbox to generate SVG from PDF, but the generated SVGs can have invalid PNG dataurl, when I try to export to pdf using doc.svg() I am getting the error 'addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added'. how to ignore this error if dataurl is not valid?

**Comment by yGuy** [comment]
I don't think there is a way. It's hard enough already to render valid SVGs properly. This library does not have the goal to validate and fix invalid SVGs. So I propose a preprocessing that removes or fixes or whatever is appropriate the broken images before passing it to this library. Maybe you can fix Apache PDFbox, instead?

**Comment by tangenttechno** [comment]
![sample](https://github.com/yWorks/svg2pdf.js/assets/112683333/2920aa94-d234-44f3-be09-69b5a59bc468)
@yGuy Thank you for the quick reply, one thing  I noticed is library is trying to fetch invalid dataURL, please see attached SVG for the original, below is the URL library is trying to fetch 

data:image/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAYAAABX5MJvAAAA1UlEQVR4Xu2WQQqD%0AMBBFsyh4A8Vd915Aj2oPUc9U7Dk6/bMohGFak1GZQPPgI2rmTRA1CaFSqZwAUbgg%0AVz7Ke6eChiNyQ54IReFzvj7KmsOAvEPuovG38LhOOnYB4YA8lGa/wuMH6TIBUWuY%0AQDyRVjqzgWRR5DlZpDMLCCZFaskk3cmgeFaElszSnQyKV0VoySrdSaCwQV6K0BL2%0ANLLHJijqFdme9LLHJlTCk2DI+51gqJCvw/8/wZD3H5OhEtYOhrxX0Q/kvZ+IIc+d%0AlQZ57TErlb/hDbwZp8G79kS6AAAAAElFTkSuQmCC;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAYAAABX5MJvAAAA1UlEQVR4Xu2WQQqDMBBFsyh4A8Vd915Aj2oPUc9U7Dk6/bMohGFak1GZQPPgI2rmTRA1CaFSqZwAUbggVz7Ke6eChiNyQ54IReFzvj7KmsOAvEPuovG38LhOOnYB4YA8lGa/wuMH6TIBUWuYQDyRVjqzgWRR5DlZpDMLCCZFaskk3cmgeFaElszSnQyKV0VoySrdSaCwQV6K0BL2NLLHJijqFdme9LLHJlTCk2DI+51gqJCvw/8/wZD3H5OhEtYOhrxX0Q/kvZ+IIc+dlQZ57TErlb/hDbwZp8G79kS6AAAAAElFTkSuQmCC
<img width="529" alt="Screenshot 2023-07-21 at 3 59 54 PM" src="https://github.com/yWorks/svg2pdf.js/assets/112683333/05d10c07-9434-4230-b024-1dfd5792e555">
<img width="1088" alt="Screenshot 2023-07-21 at 4 00 31 PM" src="https://github.com/yWorks/svg2pdf.js/assets/112683333/1fa03cdb-d47b-4fa7-aa74-1cc556a7e217">

all the invalid URL has two 'data:image' appended which is not in the original, is it related to the library since what I am doing is downloading SVG and exporting to PDF.


`<html>

<head>
    <script src="node_modules/jspdf/dist/jspdf.umd.min.js"></script>
    <script src="node_modules/svg2pdf.js/dist/svg2pdf.umd.min.js"></script>

</head>

<body>

    <script>
        // Function to download SVG from URL and save as PDF
        function downloadSVGAsPDF(url, x, y, width, height) {
          fetch(url)
            .then((response) => response.text())
            .then((svgContent) => {
              const doc = new jspdf.jsPDF();
      
              // Create a temporary div element to render the SVG
              const div = document.createElement('div');
              div.innerHTML = svgContent;
              const element = div.querySelector('svg');
      
              doc.svg(element, {
                x,
                y,
                width,
                height,
              }).then(() => {
                // Save the created PDF
                doc.save('myPDF.pdf');
              });
            })
            .catch((error) => {
              console.error('Error fetching SVG:', error);
            });
        }
      
        // Call the function with the URL of the SVG file and coordinates
        const svgUrl = 'sample.svg';
        const x = 0;
        const y = 0;
        const width = 200;
        const height = 200;
      
        downloadSVGAsPDF(svgUrl, x, y, width, height);
      </script>
</body>

</html>`

**Comment by HackbrettXXX** [comment]
The "data:image" is added here:
https://github.com/yWorks/svg2pdf.js/blob/master/src/nodes/image.ts#L77

And I suppose this method fails when trying to parse the broken data URL:
https://github.com/yWorks/svg2pdf.js/blob/master/src/nodes/image.ts#L107C17-L135

However, I agree with @yGuy. You should pass valid URLs to svg2pdf. Svg2pdf cannot detect or fix broken URLs.

**Comment by tangenttechno** [comment]
@HackbrettXXX Thank you for the reply, if you inspect the SVG file I attached, we cannot find any png data url given above. Not sure how it came, if you execute the simple sample code i have provided, you will get the same error. Can you try?

**Comment by tangenttechno** [comment]
@yGuy Thank you for the reply. Yes, your solution worked. I minified the SVG and now its rendering fine. Thank you.
