### ISSUE TITLE
greek letters in text

### ISSUE THREAD

**Issue by hjw8707** [yWorks/svg2pdf.js#265]
**Describe the bug**
I tried to make a pdf file from the svg including greek letters in text,
but the resulted pdf is not as expected.

**To Reproduce**
See this [playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%253EHello%252C%2520world%21%2520%253F%253F*%2520%25CE%25B1%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

**Expected behavior**
I would have expected the PDF to look like so. 
This is in accordance to the following SVG spec.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 115.0.5790.170

**Additional context**

**Comment by yGuy** [comment]
https://github.com/yWorks/svg2pdf.js#concerning-custom-fonts-and-non-us-ascii-characters
