### ISSUE TITLE
Fill and stroke attributes are not inherited from parent element

### ISSUE THREAD

**Issue by TorsteinHonsi** [yWorks/svg2pdf.js#27]
Live demo: https://jsfiddle.net/highcharts/7r9r26vL/1/

Expected attributes on the parent group to cascade down to children.

**Comment by yGuy** [comment]
Spec: https://www.w3.org/TR/SVG/painting.html#InheritanceOfPaintingProperties

**Comment by yGuy** [comment]
We should improve the code in https://github.com/yWorks/svg2pdf.js/blob/master/src/svg2pdf.js#L137 to walk upwards in the node element hierarchy to find the value if none is specified locally.

**Comment by HackbrettXXX** [comment]
I decided to use a "top down"/state approach where all inheritable attributes are passed to child nodes and overwritten when the child nodes specify the respective attributes themselves. Seems to be clearer to me and attributes don't have to be read several times.

**Comment by TorsteinHonsi** [comment]
Thanks so much! Will you build a new release or will you add more fixes first?

**Comment by yGuy** [comment]
We're currently doing a round of bug fixing and will release a new build sometime in the next two weeks.
