### ISSUE TITLE
Incorrect Gradient rendering in svg2pdf

### ISSUE THREAD

**Issue by santthosh7** [yWorks/svg2pdf.js#275]
Hi All,

We are using svg2pdf , and we observed that linear gradient renders differently in html as compared to the pdf generated by svg2pdf. Issue is reproducible In this Svg2Pdf [playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520width%253D%2522400%2522%2520height%253D%2522150%2522%253E%250A%2520%2520%253Cdefs%253E%250A%2520%2520%2520%2520%253ClinearGradient%2520id%253D%2522grad1%2522%2520x1%253D%25220%2522%2520x2%253D%2522100%2525%2522%2520y2%253D%25220%2522%2520y1%253D%25220%2522%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520id%253D%2522x1%2522%2520stop-color%253D%2522green%2522%2520offset%253D%25220%2525%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520id%253D%2522x2%2522%2520stop-color%253D%2522green%2522%2520offset%253D%25225%2525%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520id%253D%2522x3%2522%2520stop-color%253D%2522red%2522%2520offset%253D%25225%2525%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520id%253D%2522x4%2522%2520stop-color%253D%2522red%2522%2520offset%253D%2522100%2525%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%253C%252FlinearGradient%253E%250A%2520%2520%253C%252Fdefs%253E%250A%2520%2520%253Crect%2520x%253D%252210%2522%2520y%253D%252210%2522%2520width%253D%2522100%2522%2520height%253D%2522100%2522%2520fill%253D%2522url%28%2523grad1%29%2522%253E%253C%252Frect%253E%250A%253C%252Fsvg%253E),

We went through open issues of svg2pdf, and realised that there are some issues with percentage values for x and y attributes of linear gradient, so as a workaround we modified those to a value without percentage (100% --> 1) . This seems to fix the above issue but leads to another problem:  When stop offsets are quite small , like 1 percent or less, then in the UI, that stop gradient is barely visible , but in the generated pdf it is significantly bigger. This Issue is reproducible [here](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520height%253D%2522150%2522%2520width%253D%2522400%2522%253E%250A%2520%2520%253Cdefs%253E%250A%2520%2520%2520%2520%253ClinearGradient%2520y1%253D%25220%2522%2520y2%253D%25220%2522%2520x2%253D%25221%2522%2520x1%253D%25220%2522%2520id%253D%2522grad1%2522%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520offset%253D%25220%2525%2522%2520stop-color%253D%2522green%2522%2520id%253D%2522x1%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520offset%253D%25221%2525%2522%2520stop-color%253D%2522green%2522%2520id%253D%2522x2%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520offset%253D%25221%2525%2522%2520stop-color%253D%2522red%2522%2520id%253D%2522x3%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%2520%2520%253Cstop%2520offset%253D%2522100%2525%2522%2520stop-color%253D%2522red%2522%2520id%253D%2522x4%2522%253E%253C%252Fstop%253E%250A%2520%2520%2520%2520%253C%252FlinearGradient%253E%250A%2520%2520%253C%252Fdefs%253E%250A%2520%2520%253Crect%2520fill%253D%2522url%28%2523grad1%29%2522%2520height%253D%2522100%2522%2520width%253D%2522100%2522%2520y%253D%252210%2522%2520x%253D%252210%2522%253E%253C%252Frect%253E%250A%253C%252Fsvg%253E)

Please guide us here so that we have a consistent behaviour in both places (UI and PDF)

Thanks , 
Santhosh

**Comment by HackbrettXXX** [comment]
Yes, units are not supported: #154.

The other issue is also known. It's an issue in jsPDF: gradients are sampled at 21 equidistant points. This makes hard edges look washed-out.
https://github.com/parallax/jsPDF/blob/5d09af9135a2fe049c7d3c8b95df280d22e4a6db/src/jspdf.js#L2080-L2121
I believe there is a better way to realize gradients in PDF, but I'm not sure about the details. Please create an issue or pull request on jsPDF side.
