### ISSUE TITLE
SVG "display" Attribute Ignored

### ISSUE THREAD

**Issue by CCInc** [yWorks/svg2pdf.js#28]
When an svg element has `display="none"` set, that element is rendered anyways, resulting in an incorrect pdf to be generated.

Example: https://jsfiddle.net/7r9r26vL/2/

**Comment by yGuy** [comment]
We need to take into account display and visibility as defined here: https://www.w3.org/TR/SVG11/painting.html#VisibilityControl

**Comment by TorsteinHonsi** [comment]
+1

We have a case where the `g` element has `visibility="hidden"`, but its content is rendered anyway.

**Comment by TorsteinHonsi** [comment]
Thanks for the fix!

It still fails for `tspan` nested inside `text` inside a hidden group. To reproduce, add this snippet to the SVG in test25.html:

```xml
    <g visibility="hidden">
      <text x="20" y="60" fill="white">
        <tspan>Invisible, second level</tspan>
      </text>
    </g>
```

Output: 
![skjermbilde 2017-09-13 kl 11 57 34](https://user-images.githubusercontent.com/227836/30371415-caa54bd4-987a-11e7-82a4-748530e2fcb7.png)

**Comment by HackbrettXXX** [comment]
I think I fixed it, could you check it?

**Comment by TorsteinHonsi** [comment]
Yes, works perfectly for my case.
