### ISSUE TITLE
 Chinese garbled characters

### ISSUE THREAD

**Issue by xu-guo204** [yWorks/svg2pdf.js#280]
**Describe the bug**

**To Reproduce**
See this [playground](file:///D:/learn/svg2pdf.js/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520y%253D%252220%2522%2520x%253D%252220%2522%253E%25E9%25A5%25BF%25E4%25BA%2586%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

**Expected behavior**
I would have expected the PDF to look like so. 
This is in accordance to the following SVG spec.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yGuy** [comment]
https://github.com/yWorks/svg2pdf.js?tab=readme-ov-file#concerning-custom-fonts-and-non-us-ascii-characters
