### ISSUE TITLE
marker-start not rotating

### ISSUE THREAD

**Issue by lisizeilinger** [yWorks/svg2pdf.js#291]
When there are marker definitions for marker-start and marker-end, the marker-start element is not rotated according to the orient-attribute. It is always pointing in the same direction (and it seems that it cannot be influenced by anything)
SVG:
<img width="145" alt="Bildschirmfoto 2024-06-10 um 09 14 48" src="https://github.com/yWorks/svg2pdf.js/assets/5549075/ff6b350a-8e45-4c9e-b889-4e46cb4b226e">
PDF:
<img width="157" alt="Bildschirmfoto 2024-06-10 um 09 14 53" src="https://github.com/yWorks/svg2pdf.js/assets/5549075/5982e7a1-dd11-485a-96a8-51489d5fbffc">

SVG-Code for reproduction:
` <svg width="100%" height="100%" viewBox="-900 -200  1700 1200"><defs><marker id="arrowhead" viewBox="0 0 10 10" markerWidth="10" markerHeight="10" refX="10" refY="5" orient="auto-start-reverse" overflow="visible"><polygon points="0,0 10,5 0,10" fill="black"></polygon><line x1="10" y1="0" x2="10" y2="10" stroke="black" stroke-width="2"></line></marker><marker id="arrowfoot" markerWidth="10" markerHeight="10" refX="10" refY="5"><polygon points="0,0 10,5 0,10" fill="black"></polygon><line x1="10" y1="0" x2="10" y2="10" stroke="black" stroke-width="2"></line></marker></defs><path d="M -70 0 L -70 600" stroke="black" marker-end="url(#arrowhead)" marker-start="url(#arrowhead)" stroke-width="2"></path></svg>`

[online playground](https://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%2520%253Csvg%2520viewBox%253D%2522-900%2520-200%2520%25201700%25201200%2522%2520height%253D%2522100%2525%2522%2520width%253D%2522100%2525%2522%253E%253Cdefs%253E%253Cmarker%2520overflow%253D%2522visible%2522%2520orient%253D%2522auto-start-reverse%2522%2520refY%253D%25225%2522%2520refX%253D%252210%2522%2520markerHeight%253D%252210%2522%2520markerWidth%253D%252210%2522%2520viewBox%253D%25220%25200%252010%252010%2522%2520id%253D%2522arrowhead%2522%253E%253Cpolygon%2520fill%253D%2522black%2522%2520points%253D%25220%252C0%252010%252C5%25200%252C10%2522%253E%253C%252Fpolygon%253E%253Cline%2520stroke-width%253D%25222%2522%2520stroke%253D%2522black%2522%2520y2%253D%252210%2522%2520x2%253D%252210%2522%2520y1%253D%25220%2522%2520x1%253D%252210%2522%253E%253C%252Fline%253E%253C%252Fmarker%253E%253Cmarker%2520refY%253D%25225%2522%2520refX%253D%252210%2522%2520markerHeight%253D%252210%2522%2520markerWidth%253D%252210%2522%2520id%253D%2522arrowfoot%2522%253E%253Cpolygon%2520fill%253D%2522black%2522%2520points%253D%25220%252C0%252010%252C5%25200%252C10%2522%253E%253C%252Fpolygon%253E%253Cline%2520stroke-width%253D%25222%2522%2520stroke%253D%2522black%2522%2520y2%253D%252210%2522%2520x2%253D%252210%2522%2520y1%253D%25220%2522%2520x1%253D%252210%2522%253E%253C%252Fline%253E%253C%252Fmarker%253E%253C%252Fdefs%253E%253Cpath%2520stroke-width%253D%25222%2522%2520marker-start%253D%2522url%28%2523arrowhead%29%2522%2520marker-end%253D%2522url%28%2523arrowhead%29%2522%2520stroke%253D%2522black%2522%2520d%253D%2522M%2520-70%25200%2520L%2520-70%2520600%2522%253E%253C%252Fpath%253E%253C%252Fsvg%253E)

**Comment by yGuy** [comment]
This is because the "orient" property is not honored and specifically we always assume auto/0.

See [spec](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/orient)

This is a missing feature. Workaround would be to use two markers for either end and not depend on `auto-start-reverse`
