### ISSUE TITLE
Several tSpan's won't render correctly

### ISSUE THREAD

**Issue by henrikskar** [yWorks/svg2pdf.js#3]
Hi,

I'm working on implementing this script in a use case with Highcharts, and I've found that if there's several tSpans on the same line, svg2pdf.js won't render correctly. I've made a fork of my own, and was wondering if you'd want to take a look at it. [Highcharts fork](https://github.com/highcharts/svg2pdf.js)

The issue is that the svg2pdf.js doesn't seem to care about the x and the y coordinates. It also has problems rendering bold and italic properties inside tSpan elements. 

Are you open for suggestions as in the form of pull request?

Best regards,
Henrik Skar

**Comment by HackbrettXXX** [comment]
Hello Henrik Skar,

I've had a short look on your fork. Please create a pull request.

Regards,
Lukas Holländer

**Comment by henrikskar** [comment]
Hi Lukas,

I'll organize my branches so it'll be easier for you to look through it, and I'll update you here as they are ready. 

Thank you so much!

Best regards,
Henrik

**Comment by TorsteinHonsi** [comment]
Closed by fa0890bd1e1e601f6fb62815df409d6ee376cd8d
