### ISSUE TITLE
Font is not preserved in output

### ISSUE THREAD

**Issue by memeplex** [yWorks/svg2pdf.js#302]
**Describe the bug**

> What version are you using (exact version of svg2pdf.js and jspdf)?

I'm using the Playground.

**To Reproduce**

1. Open this in Excalidraw: https://excalidraw.com/#json=uT2u18lm6thJhSeMlnJgk,D2WWY3vMwAOmzQtwy-FZYA
2. Select the text and in the context menu press Copy to clipboard as SVG
3. Copy the text into the playground

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/7c76e5ed-0704-4c29-a55c-8acda398be57">

**Expected behavior**

The font in the PDF should be the one in the SVG.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4.1
 - Browser: Chrome 
 - Version: 127

**Comment by yGuy** [comment]
Please see the readme section on custom fonts.

https://github.com/yWorks/svg2pdf.js?tab=readme-ov-file#concerning-custom-fonts-and-non-us-ascii-characters
