### ISSUE TITLE
Support fill-rule="evenodd" on group elements

### ISSUE THREAD

**Issue by CasperVerswijvelt** [yWorks/svg2pdf.js#305]
**Is your feature request related to a problem? Please describe.**
When creating a SVG using [MakerJS](https://github.com/Microsoft/maker.js), fill and fill-rule attributes are applied to a group element instead of the path itself, like this:
```
<svg width="80mm" height="80mm" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
  <g id="svgGroup" stroke-linecap="round" fill-rule="evenodd" font-size="9pt" stroke="black" stroke-width="0" fill="black" style="stroke:black;stroke-width:0;fill:black">
    <path d="M 65.25 21.912 A 11.691 11.691 0 0 0 56.767 18.416 A 12.916 12.916 0 0 0 56.415 18.421 C 52.785 18.52 49.611 20.147 47.554 22.747 A 11.633 11.633 0 0 0 45.09 30.038 C 45.09 33.691 46.972 37.343 50.181 39.17 C 46.252 40.941 44.038 44.925 44.038 49.187 A 13.767 13.767 0 0 0 44.066 50.054 C 44.304 53.831 46.096 56.995 48.839 59.047 A 13.137 13.137 0 0 0 56.767 61.584 A 14.575 14.575 0 0 0 58.129 61.52 C 64.648 60.909 69.496 55.92 69.496 49.187 C 69.496 44.925 67.282 40.941 63.353 39.17 C 66.563 37.343 68.445 33.691 68.445 30.038 A 12.94 12.94 0 0 0 68.436 29.566 C 68.325 26.52 67.14 23.866 65.25 21.912 Z M 10.505 48.271 A 13.591 13.591 0 0 0 24.17 61.584 A 14.246 14.246 0 0 0 24.525 61.579 A 13.59 13.59 0 0 0 37.84 47.914 A 14.455 14.455 0 0 0 37.836 47.557 A 13.646 13.646 0 0 0 24.17 34.134 A 14.188 14.188 0 0 0 23.813 34.138 A 13.653 13.653 0 0 0 10.501 47.914 A 14.317 14.317 0 0 0 10.505 48.271 Z M 24.17 38.229 A 9.049 9.049 0 0 0 18.702 39.989 C 16.454 41.661 15.063 44.366 14.937 47.407 A 10.945 10.945 0 0 0 14.928 47.859 A 9.961 9.961 0 0 0 17.27 54.416 C 18.905 56.306 21.302 57.488 24.17 57.488 A 9.092 9.092 0 0 0 29.588 55.781 C 31.977 54.042 33.413 51.14 33.413 47.859 A 9.862 9.862 0 0 0 30.553 40.771 C 29.048 39.296 27.022 38.352 24.649 38.24 A 10.141 10.141 0 0 0 24.17 38.229 Z M 56.767 41.217 A 8.055 8.055 0 0 0 50.648 43.974 A 7.991 7.991 0 0 0 48.687 49.242 A 8.004 8.004 0 0 0 56.555 57.264 A 8.552 8.552 0 0 0 56.767 57.267 A 8.055 8.055 0 0 0 62.887 54.51 A 7.991 7.991 0 0 0 64.847 49.242 A 8.004 8.004 0 0 0 56.979 41.22 A 8.552 8.552 0 0 0 56.767 41.217 Z M 56.767 22.733 C 52.783 22.733 49.517 25.943 49.517 29.928 C 49.517 33.968 52.783 37.233 56.767 37.233 C 60.752 37.233 64.017 33.968 64.017 29.928 C 64.017 25.943 60.752 22.733 56.767 22.733 Z" vector-effect="non-scaling-stroke" />
  </g>
</svg>
```

Which is shown like this:
![image](https://github.com/user-attachments/assets/d886f9a8-2a76-4da5-b563-04019dd22874)

When passing this SVG to a PDF document using svg2df.js's `.svg(...)` function, this results in the following PDF file, where the fill-rule is not respected:
![image](https://github.com/user-attachments/assets/be04eea9-b556-4334-8d7f-c6b2cc769c99)

The [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g) state that its attributes are inherited by its children.

I saw that fill-rule support was added a while ago, but did not include group support: #111 

**Describe the solution you'd like**
No API changes needed, fill-rule on groups should be inherited by its children

**Describe alternatives you've considered**
I tried getting MakerJS to generate the SVG without the group element, but was unsuccessful.

**Comment by HackbrettXXX** [comment]
Thanks for the report. We'll accept a pull request for this. We probably just need to add the fill-rule to the attribute state.

**Comment by CasperVerswijvelt** [comment]
Thanks for pointing me in the right direction, adding it to the attribute state was indeed the way to go
