### ISSUE TITLE
Generation in a Node backend 

### ISSUE THREAD

**Issue by flow-kirill** [yWorks/svg2pdf.js#306]
Is it possible to get the library working in a Node backend or is it purely browser based?
Currently I get an error like this when trying to use `doc.svg` in Node:
```
TypeError: this.rootSvg.querySelectorAll is not a function
```

**Comment by yGuy** [comment]
If you find a working DOM implementation in your Node backend, that would work. However, to the best of my knowledge there is no (not even half-way) complete DOM implementation for Node available. Specifically, for the SVG elements (which this project is all about) it's basically below 5% implementation complete when you look at things like what Jest uses, e.g.

So, yes, this package is meant to be used in an HTML5 environment like the browser. If you are on the server, run your SVGs through some binaries that creates the PDF, e.g. the browser itself.
