### ISSUE TITLE
Orientation is not supported

### ISSUE THREAD

**Issue by asitatmicello** [yWorks/svg2pdf.js#31]
setting jsPDF orientation option does not change anything. Looks like there are few lines commented in this version of jsPDF lib which prevents it from rotating.

**Comment by HackbrettXXX** [comment]
This is probably a duplicate of [this](https://github.com/yWorks/jsPDF/pull/4) pull request. There is a fix on the way, it will come with the next release.

**Comment by asitatmicello** [comment]
Thanks!!
I was also wondering if you guys have any plan to support addImage function of jsPDF.

**Comment by yGuy** [comment]
In what way do you want us to support addImage? Converting SVG to PDF does not require that functionality, or does it? Please be more specific and ideally file a new issue if you think this is something that should be addressed.

**Comment by asitatmicello** [comment]
Ok, let me create a new issue.
