### ISSUE TITLE
issue with object transform

### ISSUE THREAD

**Issue by poplevente** [yWorks/svg2pdf.js#32]
Hi Guys,

i have the following svg, which has a yellow rounded corner object with a text in it, but in the pdf it converts it to a black box instead. can someone help me identify why is that happening?

svg:
`<svg id="svgElement" width="600px" height="600px" GL="0 0 1315 301" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g transform="matrix(1, 0, 0, 1, 0, 0)" clip-path="url(#mainClip5855)">
    <rect x="0" y="0" width="1315" height="301" fill="white" stroke="none" transform="matrix(1, 0, 0, 1, 0, 0)"/>
    <g transform="matrix(1, 0, 0, 1, 30, 1)">
      <g transform="matrix(1, 0, 0, 1, 180, 72)">
        <g transform="matrix(1, 0, 0, 1, 0, 0)">
          <g transform="matrix(1, 0, 0, 1, 0, 0)" filter="url(#SHADOW5859)">
            <filter id="SHADOW5859" x="-100%" y="-100%" width="300%" height="300%">
              <feGaussianBlur in="SourceAlpha" result="blur" wL="2"/>
              <feFlood in="blur" result="flood" flood-color="rgba(0, 0, 0, 0.3)"/>
              <feComposite in="flood" in2="blur" operator="in" result="comp"/>
              <feOffset in="comp" result="offsetBlur" dx="0" dy="2"/>
              <feMerge>
                <feMergeNode in="offsetBlur"/>
                <feMergeNode in="SourceGraphic"/>
              </feMerge>
            </filter>
            <path d="M 0,2 L 0,2.0000000000000004 A 2,2 90 0,1 1.9999999999999996,0 L 127,0 L 127,0 A 2,2 90 0,1 129,1.9999999999999996 L 129,79 L 129,79 A 2,2 90 0,1 127,81 L 2,81 L 2,81 A 2,2 90 0,1 0,79 L 0,2 z" fill="url(#GRAD5860)" stroke="none" transform="matrix(1, 0, 0, 1, 1.5, 1.5)"/>
            <path d="M 0,2 L 0,2.0000000000000004 A 2,2 90 0,1 1.9999999999999996,0 L 127,0 L 127,0 A 2,2 90 0,1 129,1.9999999999999996 L 129,79 L 129,79 A 2,2 90 0,1 127,81 L 2,81 L 2,81 A 2,2 90 0,1 0,79 L 0,2 z" fill="none" stroke="url(#GRAD5861)" stroke-width="3" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" transform="matrix(1, 0, 0, 1, 1.5, 1.5)"/>
          </g>
          <g transform="matrix(1, 0, 0, 1, 0, 0)">
            <path d="M 0,2 L 0,2.0000000000000004 A 2,2 90 0,1 1.9999999999999996,0 L 130,0 L 130,0 A 2,2 90 0,1 132,1.9999999999999996 L 132,14 L 0,14 z" fill="transparent" stroke="none" transform="matrix(1, 0, 0, 1, 0, 0)"/>
          </g>
          <text x="66" y="9.866995239257813" text-anchor="middle" opacity="0.54" fill="black" stroke="none" transform="matrix(1, 0, 0, 1, 0, 35)">Text 1</text>
        </g>
      </g>
     </g>
  </g>
  <clipPath id="mainClip5855">
    <rect x="0" y="0" width="1315" height="301"/>
  </clipPath>
  <clipPath id="CLIP5858">
    <path d="M 24,5 L 299,5 L 299,21 L 24,21 z" opacity="0.8" transform="matrix(1, 0, 0, 1, 0, 0)"/>
  </clipPath>
  <linearGradient x1="0" x2="129" y1="40.5" y2="40.5" id="GRAD5860" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#FFD378"/>
    <stop offset="1" stop-color="#FFC857"/>
  </linearGradient>
  <linearGradient x1="0" x2="129" y1="40.5" y2="40.5" id="GRAD5861" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#FFD378 "/>
    <stop offset="1" stop-color="#FFC857"/>
  </linearGradient>
</svg>`

thanks!

**Comment by yGuy** [comment]
The SVG is _much_ more complicated than your description: - it has filters, which aren't supported at all and complex gradients, plus complex clip paths. Try stripping down the SVG and see what works for you and what doesn't. If you want to render this SVG using svg2pdf there will probably more than just issue that needs to be addressed. If you can, use a simpler SVG (rendering something similar can be done in less than one tenth of the size).

**Comment by poplevente** [comment]
okay, thank you for your answer. will try to strip the svg

**Comment by poplevente** [comment]
i see that even a simple gradient isn't working and becomes black : 
`  <rect fill="url(#GRAD5861)"
          x="10" y="10" width="100" height="100"/>
   ....
  <linearGradient id="GRAD5861">
    <stop offset="5%" stop-color="green"/>
    <stop offset="95%" stop-color="gold"/>
  </linearGradient>`

does the lib supports gradients?

**Comment by HackbrettXXX** [comment]
The library does support gradients. However, "%"-measures are not supported.

**Comment by poplevente** [comment]
even without % it's black
`
  <linearGradient id="GRAD5861">
		<stop offset="0" stop-color="red"/>
        <stop offset="1" stop-color="blue"/>
  </linearGradient>
`

**Comment by HackbrettXXX** [comment]
There actually two bugs here:
1. the default values for ```x1, x2, y1, y2``` are not specified and resulted in "NaN"
2. the ```linearGradient``` element is specified after its usage and not within a ```defs``` element. I'm not sure if this is a bug or not, as e.g. MDN [states](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients):
>  Gradients are defined in a defs section as opposed to on a shape itself to promote reusability

The workaround would be to define the ```x1, x2, y1, y2``` values (0, 1, 0, 0) and wrap the ```linearGradient``` with a ```defs```

**Comment by HackbrettXXX** [comment]
Just fixed bug No 1.

**Comment by poplevente** [comment]
yes, thanks! works this way.

**Comment by poplevente** [comment]
One more question. do you support to have a gradient for the stroke?
i have an element with fill gradient, which is working well. then i have another element with a stroke with the same gradient around the first element. (don't ask why, this is how gojs builds the svg :) )

`<path d="M 0,2 L 0,2.0000000000000004 A 2,2 90 0,1 1.9999999999999996,0 L 127,0 L 127,0 A 2,2 90 0,1 129,1.9999999999999996 L 129,79 L 129,79 A 2,2 90 0,1 127,81 L 2,81 L 2,81 A 2,2 90 0,1 0,79 L 0,2 z" fill="url(#GRAD6201)" stroke="none" transform="matrix(1, 0, 0, 1, 1.5, 1.5)"/>
<path d="M 0,2 L 0,2.0000000000000004 A 2,2 90 0,1 1.9999999999999996,0 L 127,0 L 127,0 A 2,2 90 0,1 129,1.9999999999999996 L 129,79 L 129,79 A 2,2 90 0,1 127,81 L 2,81 L 2,81 A 2,2 90 0,1 0,79 L 0,2 z" fill="none" stroke="url(#GRAD6202)" stroke-width="3" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" transform="matrix(1, 0, 0, 1, 1.5, 1.5)"/>
			
<defs>
	<linearGradient x1="0" x2="129" y1="40.5" y2="40.5" id="GRAD6201" gradientUnits="userSpaceOnUse">
		<stop offset="0" stop-color="#FFD378"/>
		<stop offset="1" stop-color="#FFC857"/>
	</linearGradient>
	<linearGradient x1="0" x2="129" y1="40.5" y2="40.5" id="GRAD6202" gradientUnits="userSpaceOnUse">
		<stop offset="0" stop-color="#FFD378 "/>
		<stop offset="1" stop-color="#FFC857"/>
	</linearGradient>
</defs>`

**Comment by yGuy** [comment]
No, gradient strokes aren't currently supported. Pull requests are welcome, as always. Maybe the Northwoods team would like to chime in, here? :-P

An easy workaround would be to use [yFiles for HTML](https://www.yworks.com/yfileshtml) instead ;-)  That library creates much cleaner SVG - and coincidentally this library was created with this very specific use-case in mind.

**Comment by poplevente** [comment]
thanks!
