### ISSUE TITLE
Line element: not specified coordinate

### ISSUE THREAD

**Issue by hrbaer** [yWorks/svg2pdf.js#34]
SVG documentation says: If the attribute is not specified, the effect is as if a value of "0" were specified.
Origin in line below is (0|0), but (NaN|NaN) in PDF.

`<line x2="300" y2="150" stroke-width="3" stroke="black"/>`

**Comment by yGuy** [comment]
Looks like  this line is missing some `|| 0` treatment:
https://github.com/yWorks/svg2pdf.js/blob/master/src/svg2pdf.js#L1064
@HackbrettXXX  ?

**Comment by HackbrettXXX** [comment]
That's true. I'm gonna fix it as soon as possible.

**Comment by hrbaer** [comment]
Great. The problem turned up when using D3’s scale functions.
Regards
HB

Am 14.11.2017 um 12:16 schrieb Lukas Holländer <notifications@github.com<mailto:notifications@github.com>>:


That's true. I'm gonna fix it as soon as possible.

**Comment by yGuy** [comment]
Fixed in 1.1.2
