### ISSUE TITLE
Rectangular boxes enclosing graphic elements

### ISSUE THREAD

**Issue by kickmyassp** [yWorks/svg2pdf.js#36]
Hello,
I am working on converting musical notations in SVG to PDF. Considering that I am a novice to both SVG and PDF as well as JS, svg2pdf.js has been a huge help for me.  One problem  I face now is unwanted rectangular boxes around all the graphic elements. See [this PDF file](https://drive.google.com/open?id=1PKJtA3DBFz_E_Vcf-CFkeiVe_ieTGcuL) for example. 

Any help would be greatly appreciated.

**Comment by yGuy** [comment]
In order to help you here, as small test-case would be very helpful: can you come up with a very small svg that exhibits the problem- we need the original svg in order to diagnose this.

**Comment by kickmyassp** [comment]
Thanks for your reply. Attached is a html file with an svg tag included.  The svg description  was actually created by another Javascript(abcjs) and hence is  not as small (or readable) as I would like.  

I hope this would be useful to you.
[test_svg2pdf.txt](https://github.com/yWorks/svg2pdf.js/files/1520151/test_svg2pdf.txt)

**Comment by Hackbrett3X** [comment]
Thanks for the example. The reason is that there are <rect> elements where fill-opacity and stroke-opacity are set to zero. The stroke-opacity attribute is not completely supported right now.

As a workaround you could try to find out what creates those invisible rects.

**Comment by Hackbrett3X** [comment]
I just added support for stroke-opacity. It will come with the next release.

**Comment by kickmyassp** [comment]
hello
I tried the new version(1.2.0) with the html/svg file I sent previously.  Those rects with fill-opacity and stroke-opacity set to zero are invisible in svg but still become VISIBLE in pdf.  
Is this what you meant when  you say "stroke-opacity" is supported?

**Comment by HackbrettXXX** [comment]
Hi,
are you sure you use the latest release? Unfortunately, the latest version on npm is still 1.1.2 . Right now you'll have to download/clone it from GitHub or use Bower in order to get 1.2.0.

**Comment by kickmyassp** [comment]
Hello,

I am sure I did use 1.2.0. I used git to pull the latest one.

The file header says:

/**

 * Modules in this bundle

 * @license

 *

 * svg2pdf.js:

 *   license: MIT (http://opensource.org/licenses/MIT)

 *   author: yFiles for HTML Support Team <yfileshtml@yworks.com>

 *   homepage: https://github.com/yWorks/svg2pdf.js#readme

 *   version: 1.2.0

 *

 * svgpath:

 *   license: MIT (http://opensource.org/licenses/MIT)

 *   homepage: https://github.com/fontello/svgpath#readme

 *   version: 2.2.1

 *

 * This header is generated by licensify (https://github.com/twada/licensify
)

 */

**Comment by HackbrettXXX** [comment]
Mmh, thats funny: I did a clean download from GitHub and ran your test above and I cannot see any boxes.

**Comment by kickmyassp** [comment]
It turned out that I was using an old version of jsPDF(1.2.70).  It wasn't
obvious to me I needed to update jsPDF as well as svg2pdf.
I switched to the latest one (1.3.0) and those annoying boxes are now gone.
Thanks!!!

**Comment by HackbrettXXX** [comment]
Ah, that makes sense. Sorry, forgot about that...
