### ISSUE TITLE
Add support for inlining SVG data-urls

### ISSUE THREAD

**Issue by yGuy** [yWorks/svg2pdf.js#38]
Right now, if there are images within an svg, the software loads those images and renders them into a canvas to include the bitmap into the resulting PDF. That's perfect to bitmap images, however if the image is actually an SVG (possibly even an svg data-url) then it would be awesome to include that image as a vector/SVG image, directly.

**Comment by HackbrettXXX** [comment]
Good point

**Comment by HackbrettXXX** [comment]
When it's not a data URL this would be an asynchronous operation, right? So we cannot support regular URLs...

**Comment by fskpf** [comment]
Not sure if the following is related as well or if it should be treated as separate issue:

Data-URIs that contain non-base64 svg do not work properly, e.g.
` <image preserveAspectRatio="none" href="data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22...." width="35" x="5" y="0" height="55"></image>`
or
`<image preserveAspectRatio="none" href='data:image/svg+xml,<?xml version="1.0" encoding="utf-8"?><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="36px" height="57px" viewBox="0 -0.741 36 57" enable-background="new 0 -0.741 36 57"...' width="35" x="5" y="0" height="55"></image>`

Those are not exported at all, it seems.

Using base64 encoded data-uris seem to be exported, but their position and size is not correct:
`<image preserveAspectRatio="none" href="data:image/svg+xml;base64,PD94bWwgdmVyc..." width="50" x="100" y="0" height="200"></image>`

I've put together a small test case ([data-uri_html.txt](https://github.com/yWorks/svg2pdf.js/files/2396184/data-uri_html.txt)). Note that the exported image is actually the skewed image of the input SVG (i.e. the one with the base64 image), although its layout is un-skewed in the output PDF.

Is this an issue with svg2pdf or is it garbage input?

**Comment by HackbrettXXX** [comment]
This is actually an issue of svg2pdf. I'm working on a fix.

**Comment by HackbrettXXX** [comment]
fixed two issues:
 - x, y, width, height and preserveAspectRatio were actually ignored for inline svgs
 - the parsing of non-base64 urls was incorrect
