### ISSUE TITLE
Width and height properties not working anymore

### ISSUE THREAD

**Issue by fskpf** [yWorks/svg2pdf.js#43]
The width and height properties don't seem work properly anymore. For example, take test2.html and change the code to

```javascript
    var width = 100;
    var height = 300;
    var pdf = new jsPDF('l', 'pt', [width, height]);
```
The resulting pdf is much wider than high. The same issue can be observed in  http://live.yworks.com/demos/view/pdfexport/index.html or https://www.yworks.com/yed-live/ when changing the export rectangle to be smaller than high.

This used to work in the past as far as I can remember.

**Comment by HackbrettXXX** [comment]
The reason for that is that jsPDF swaps the width and height properties when they don't match the landscape/portrait argument. Just insert something like:
```js
var pdf = new jsPDF(width > height ? 'l' : 'p', 'pt', [width, height]);
```

**Comment by fskpf** [comment]
I see. Works as expected now, thank you.
