### ISSUE TITLE
Multiple pages PDF

### ISSUE THREAD

**Issue by hausteinorg** [yWorks/svg2pdf.js#44]
It appears when I add another page to the PDF and run svg2pdf a second time, that the PDF is empty.

**Comment by HackbrettXXX** [comment]
I just tested it and could not reproduce this bug. Could you provide an example where this bug occurs?

**Comment by hausteinorg** [comment]
Please find the SVG and PDF file attached:
[template.zip](https://github.com/yWorks/svg2pdf.js/files/1671473/template.zip)

Maybe I do something wrong, please find my code snippet below:

`
function toPDF(svg, url) {
var svgElem = svg[0];
							var pdf = new jsPDF('l', 'pt', [svg.width(), svg.height()]);
							svg2pdf(svgElem, pdf, {xOffset: 0, yOffset: 0, scale: 1});
							pdf.addPage();
							svg2pdf(svgElem, pdf, {xOffset: 0, yOffset: 0, scale: 1});
							pdf.save(url);
						},
`

**Comment by HackbrettXXX** [comment]
Your code snippet is fine.

The reason for the bug is that your svg file contains a `<clipPath>` element, which is currently not supported by svg2pdf. For now, you could just omit the clip-path as it has no effect on the result (it's the same size as the svg viewbox).

**Comment by HackbrettXXX** [comment]
#45

**Comment by hausteinorg** [comment]
Without clipPath is works fine. Thanks a lot for the quick response!
