### ISSUE TITLE
Exporting large areas throws invalid size error Acrobat Reader DC

### ISSUE THREAD

**Issue by fskpf** [yWorks/svg2pdf.js#52]
Exporting large areas to PDF yields an invalid size error in Acrobat Reader DC.

Please try the attached reproduction. It will create a blank 15000x15000 PDF that is opened correctly in Chrome, but throws an error in Acrobat Reader. If the file would have content, it would be clipped.
Note that I've also attached the ouput.pdf that is generated from the test case:

[big-area-test.zip](https://github.com/yWorks/svg2pdf.js/files/2149872/big-area-test.zip)
[output.pdf](https://github.com/yWorks/svg2pdf.js/files/2149869/output.pdf)

Is this a general PDF limitation or is there something wrong in svg2pdf or jsPDF? Maybe it can be fixed.

**Comment by HackbrettXXX** [comment]
The PDF specification suggests these limits for page sizes.
> The minimum page size should be 3 by 3 units in default user space; the maximum should be 14,400 by 14,400 units.
Readers may or may not follow them. So this is an "issue" of the Acrobat Reader.
