### ISSUE TITLE
incorrect text encoding

### ISSUE THREAD

**Issue by ab2llah** [yWorks/svg2pdf.js#56]
hi.i have created the pdf file and all the shapes are in their correct place but the text is not shown correctly. here is a screen shot of the problem : 
![screen shot 2018-10-09 at 3 16 27 pm](https://user-images.githubusercontent.com/13770210/46667500-b54d9300-cbd6-11e8-9e23-510e2075de40.jpg)
any idea how to solve this issue?

**Comment by HackbrettXXX** [comment]
Can you give us the SVG that created this PDF?
Did you include all required fonts?

**Comment by HackbrettXXX** [comment]
Closing since you didn't reply. Feel free to reopen if you think this is in fact an issue with svg2pdf.
