### ISSUE TITLE
I have no idea about this issue belong to svg2pdf or jsPdf?

### ISSUE THREAD

**Issue by christee** [yWorks/svg2pdf.js#61]
It‘s not support chinese ? 

```
doc.addFont('msyh.ttf', 'msyh', 'normal');
doc.setFont('msyh');
```

Pdf exported by using doc.text is ok, 

`doc.text(20, 20, '导出标题');`

but used svg2pdf is not working, chinese became messy code.

```
svg2pdf(element, doc, {
         xOffset: 0,
         yOffset: 0,
         scale: 0.6
});
```

like this 

> SÑNºTX

Is there any way to fix this ?

**Comment by yGuy** [comment]
Please provide a short, complete example. Why would you believe that the font should be used for the SVG element?

**Comment by christee** [comment]
So, that's my confused place, i don't understand the font can applied on SVG element or not.
Code that wrote follow the docs is simple, now i don't have it.
I am care about how to convert encoding with the content of SVG element.

**Comment by yGuy** [comment]
Did you see this: https://github.com/yWorks/svg2pdf.js/blob/master/tests/custom-fonts.html ?

**Comment by christee** [comment]
Thanks, I will try this later !

**Comment by christee** [comment]
Yeah, this issue has been solved ! So appreciated for your help!
