### ISSUE TITLE
Is there a possibility to support ie9 ?

### ISSUE THREAD

**Issue by christee** [yWorks/svg2pdf.js#62]
I tried polyfill to fixed uint8array error. but there is more. Supporting ie9, any chance ?

Here is error from ie9 :

`jsPDF PubSub Error Object expected TypeError: Object expected`

**Comment by HackbrettXXX** [comment]
This seems to be an error of [yWorks/jsPDF](https://github.com/yWorks/jsPDF) or even [jsPDF](https://github.com/MrRio/jsPDF). We are not planning on adding support for ie9 ourselves. If you want, you may supply pull requests to othe respective repositories, though.
