### ISSUE TITLE
Element with fill="none" takes the color of the following element

### ISSUE THREAD

**Issue by TorsteinHonsi** [yWorks/svg2pdf.js#67]
**Describe the bug**
When an element with `fill="none"` is followed by an element with a fill, the blank element gets that fill. The same happens with `fill="transparent"`, but not with `fill="rgba(0,0,0,0)"`. 

Using svg2pdf version 1.3.0 and jspdf version 2.0.0.

**To Reproduce**
See https://jsfiddle.net/highcharts/4u28to50/

**Desktop (please complete the following information):**
- iOS Chrome, Firefox etc.

**Comment by HackbrettXXX** [comment]
Fixed.
