### ISSUE TITLE
Title elements are rendered

### ISSUE THREAD

**Issue by TorsteinHonsi** [yWorks/svg2pdf.js#74]
**Describe the bug**
When adding `<title>` elements inside `<text>` elements, they should not be rendered.

**To Reproduce**
https://jsfiddle.net/highcharts/mae0j8c5/

**Expected behavior**
Title elements should be hidden

**Desktop (please complete the following information):**
 - OS: Tested on Chrome/Mac

**Comment by yGuy** [comment]
Thanks for the report. That should be easy to fix.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
