### ISSUE TITLE
fill gradient rect not working

### ISSUE THREAD

**Issue by dippindots** [yWorks/svg2pdf.js#77]
**Describe the bug**
We rendered the gradient rect but when we download it, it turns to a single color.

**To Reproduce**
https://jsfiddle.net/zgfilx/6zh05e4k/

**Expected behavior**
we can download the gradient rect correctly.

**Desktop (please complete the following information):**
 - OS: Tested on Chrome/Mac

**Additional context**
If this is not a bug, could you tell me where I am wrong? Thanks!

**Comment by HackbrettXXX** [comment]
The reason is that you use percentage values for the stop offsets. This is currently not supported by svg2pdf. As a workaround you can use values between 0 and 1.

**Comment by dippindots** [comment]
@HackbrettXXX Thank you so much, that works perfectly. Do you have a plan to support the percentage? I may help to make a pr.

**Comment by HackbrettXXX** [comment]
Feel free to provide a pull request. Should be quite easy to implement that. Search for "offset" in the code ;)
