### ISSUE TITLE
Garbled text that ends with "..."

### ISSUE THREAD

**Issue by scottctr** [yWorks/svg2pdf.js#85]
I've got several text elements that I've truncated and added "..." so it will fit into the allotted space with an indication of the truncation. The text appears fine in the graph component, but comes out garbled in the PDF. I'm using the latest version of svg2pdf (1.3.4) and jsPdf-yworks (2.0.2). This issue seems to only occur with text I've truncated and added the dots.

**PDF**
![image](https://user-images.githubusercontent.com/29161665/58214654-25b7a900-7cbc-11e9-8e20-9297ecabddaf.png)

**Graph**
![image](https://user-images.githubusercontent.com/29161665/58214684-467ffe80-7cbc-11e9-8f11-3dca564ffca6.png)

**SVG from Graph**
```<text transform="translate(0 45)" fill="#333333" font-family="'Arial'" font-size="10px" font-style="normal" font-weight="normal"><tspan dy="1.1em" x="75" text-anchor="middle">Korea (Democratic People's…</tspan></text>```

**Comment by HackbrettXXX** [comment]
The reason is the `…` character, which is not part of the "native" Helvetica font (which is used as backup for Arial). To resolve this issue you need to embed a font that supports this Unicode character. See the [readme of jsPDF](https://github.com/yWorks/jsPDF) on how to do this.

**Comment by scottctr** [comment]
I got this to work, but had to use [this](https://github.com/MrRio/jsPDF#use-of-utf-8--ttf) instead. Also had to add ```jsPdf.setFont('Arial')```, but not sure why I had to set the font since it's set correctly in the SVG. Is it because there's an extra set of quotes around "'Arial'" (see SVG above)? That text element is being generated by ```TextRenderSupport.addText(...)```.

**Comment by HackbrettXXX** [comment]
That's curious. I cannot reproduce it. The quotes should make no difference. Could you send me the font file you are using?

**Comment by scottctr** [comment]
Font file attached -- thanks! [arial-normal.zip](https://github.com/yWorks/svg2pdf.js/files/3216790/arial-normal.zip)

**Comment by HackbrettXXX** [comment]
Your font file works for me. Did you maybe load the scripts in the wrong order? The font file needs to be loaded after jsPDF. Otherwise the jsPdf-API is undefined.

**Comment by scottctr** [comment]
You're correct about loading the scripts out of order -- thanks!
