### ISSUE TITLE
Axises in svg-diagram do not render correctly on PDF

### ISSUE THREAD

**Issue by Fadiabb** [yWorks/svg2pdf.js#89]
Exporting svg-diagram to pdf does not draw the x-axis, y-axis correctly
using the following example: https://gist.github.com/Fadiabb/093859a7fdc1e2565ca60db2455885c5
will generate pdf with clearly thicker axis.
 
* the orginal svg-diagram on html page:
![svg-diagram-screenshot](https://user-images.githubusercontent.com/39081670/59094327-2b48fc00-8916-11e9-833f-b5ce957b7bca.png)

* generated on PDF: 
![svg-diagram-screenshot3](https://user-images.githubusercontent.com/39081670/59094521-97c3fb00-8916-11e9-927e-284cf3e671b5.png)
 results: thicker x-axis and small lines on y-axis 

**Tested with:**
  * Mozila Firefox 60.5.1esr (64-bit)
  *  OS: Linux version 4.19.0-4-amd64 , SMP Debian 4.19.28-2
  * svg2pdf v.1.3.4 and jspdf v.2.0.2

**Comment by Fadiabb** [comment]
```xml 
<path class="domain" stroke="black" d="M-6,242.5H0.5V0.5H-6"></path>
```
does not render  properly on PDF

**Comment by yGuy** [comment]
Thank you for your reports - please create a complete test-case. It's simple: provide a self-contained, minimal svg and describe exactly what you were expecting. In this case the problem could be due to the "domain" class not being treated correctly, however we cannot know.

**Comment by yGuy** [comment]
I think I was wrong, I think the problem is due to the fill="none" not being inherited and it hasn't got anything to do with the classes. Looks like this is the same issue as in https://github.com/yWorks/svg2pdf.js/issues/87#issuecomment-499100787
