### ISSUE TITLE
Support for some jspdf functions 

### ISSUE THREAD

**Issue by Fadiabb** [yWorks/svg2pdf.js#90]
Hallo, 
The following jspdf functions are not supported in yWork-jspdf Fork : 
getLineHeightFactor()
setLineDash()

trying to use them : 
```html
<html>
<script src="../node_modules/jspdf-yworks/dist/jspdf.min.js"></script>
<body>
<script>
 const pdf = new jsPDF("l", "mm", "a3");
   pdf.setLineDash();
   pdf.getLineHeightFactor();
</script>
</body>
</html>
```
throws Errors: 
 Uncaught TypeError: pdf.getLineHeightFactor is not a function
 Uncaught TypeError: pdf.setLineDash is not a function

**Comment by yGuy** [comment]
Is there a use-case for these functions in SVG2PDF? Please elaborate. 
If this is an issue for our jspdf fork, then please file the issue with the respective project and be sure to provide the details.

**Comment by Fadiabb** [comment]
ok i will report it again by yWork-jsPDF
